### ISSUE TITLE
tweeter feeds are empty

### ISSUE THREAD

**Issue by zoubidabida** [zedeus/nitter#916] opened 2023-06-30 08:33 UTC
Hi !

my tweeter feeds went empty sometime last night.
I checked and the headers are shown, but there is absolutely no tweet in them.
It says "No items found".
I have the latest version installed, and no update was made since may, I believe.
Other instances seem to work, what could I do to correct mine ?

thanks 

here's a sample output I'm getting : 
`GET /GreatDismal

HTTP/1.1 200 OK
content-type: text/html;charset=utf-8
Content-Length: 7439

<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="/css/style.css?v=18" />
    <link rel="stylesheet" type="text/css" href="/css/fontello.css?v=2" />
    <link rel="stylesheet" type="text/css" href="/css/themes/nitter.css" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
    <link rel="manifest" href="/site.webmanifest" />
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#ff6c60" />
    <link rel="search" type="application/opensearchdescription+xml" title="nitter" href="http://127.0.0.1/opensearch" />
    <link rel="canonical" href="https://twitter.com/GreatDismal" />
    <link rel="alternate" type="application/rss+xml" href="/GreatDismal/rss" title="RSS feed" />
    <title>William Gibson (@GreatDismal)|nitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#1F1F1F" />
    <meta property="og:type" content="object" />
    <meta property="og:title" content="William Gibson (@GreatDismal)" />
    <meta property="og:description" content="Author of Neuromancer, The Peripheral, Agency… I’m also @greatdismal.bsky.social" />
    <meta property="og:site_name" content="Nitter" />
    <meta property="og:locale" content="en_US" />
    <link rel="preload" type="image/png" href="/pic/https%3A%2F%2Fpbs.twimg.com%2Fprofile_banners%2F28049003%2F1681950675%2F1500x500" as="image" />
    <link rel="preload" type="image/png" href="/pic/pbs.twimg.com%2Fprofile_images%2F1648847697150103552%2FVbCybNN1_400x400.jpg" as="image" />
    <meta property="og:image" content="http://127.0.0.1/pic/pbs.twimg.com%2Fprofile_images%2F1648847697150103552%2FVbCybNN1_400x400.jpg" />
    <meta property="twitter:image:src" content="http://127.0.0.1/pic/pbs.twimg.com%2Fprofile_images%2F1648847697150103552%2FVbCybNN1_400x400.jpg" />
    <meta property="twitter:card" content="summary" />
    <link rel="preload" type="font/woff2" as="font" href="/fonts/fontello.woff2?21002321" crossorigin="anonymous" />
  </head>
  <body>
    <nav><div class="inner-nav">
        <div class="nav-item"><a class="site-name" href="/">nitter</a></div>
        <a href="/"><img class="site-logo" src="/logo.png" alt="Logo" /></a>
        <div class="nav-item right">
          <div class="icon-container"><a class="icon-search" title="Search" href="/search"></a></div>
          <div class="icon-container"><a class="icon-rss-feed" title="RSS Feed" href="/GreatDismal/rss"></a></div>
          <div class="icon-container"><a class="icon-bird" title="Open in Twitter" href="https://twitter.com/GreatDismal"></a></div>
          <a href="https://liberapay.com/zedeus"><svg class="lp" viewBox="0 0 40.6 52.3">
  <g transform="matrix(0.83,0,0,0.83,-158,-261)">
    <path d="m202.5,366c-3.1 0-5.5-0.4-7.3-1.2-1.8-0.8-3-1.9-3.8-3.3-0.8-1.4-1.1-3-1.1-4.8 0-1.8 0.3-3.7 0.8-5.8l8.3-34.8 10.2-1.6-9.1 37.8c-0.2 0.8-0.3 1.5-0.3 2.2 0 0.7 0.1 1.2 0.4 1.7 0.3 0.5 0.7 0.9 1.3 1.2 0.6 0.3 1.5 0.5 2.7 0.6l-2 8.1"/>
    <path d="m239.2 344.3c0 3.2-0.5 6.1-1.6 8.8-1 2.6-2.5 4.9-4.4 6.9-1.9 1.9-4.1 3.4-6.7 4.5-2.6 1.1-5.4 1.6-8.5 1.6-1.5 0-3-0.1-4.5-0.4l-3 11.9h-9.7l10.9-45.4c1.7-0.5 3.7-1 6-1.4 2.3-0.4 4.7-0.6 7.3-0.6 2.4 0 4.6 0.4 6.3 1.1 1.8 0.7 3.2 1.8 4.4 3 1.1 1.3 2 2.8 2.5 4.5 0.5 1.7 0.8 3.6 0.8 5.5m-23.8 13.4c0.7 0.2 1.7 0.3 2.8 0.3 1.7 0 3.3-0.3 4.7-1 1.4-0.6 2.6-1.5 3.6-2.7 1-1.1 1.7-2.5 2.3-4.1 0.5-1.6 0.8-3.4 0.8-5.3 0-1.9-0.4-3.5-1.2-4.8-0.8-1.3-2.3-2-4.3-2-1.4 0-2.7 0.1-3.9 0.4l-4.6 19.1"/>
  </g>
</svg>
</a>
          <div class="icon-container"><a class="icon-info" title="About" href="/about"></a></div>
          <div class="icon-container"><a class="icon-cog" title="Preferences" href="/settings?referer=%2FGreatDismal"></a></div>
        </div>
      </div></nav>
    <div class="container"><div class="profile-tabs">
        <div class="profile-banner"><a href="/pic/https%3A%2F%2Fpbs.twimg.com%2Fprofile_banners%2F28049003%2F1681950675%2F1500x500" target="_blank"><img src="/pic/https%3A%2F%2Fpbs.twimg.com%2Fprofile_banners%2F28049003%2F1681950675%2F1500x500" alt="" loading="lazy" decoding="async" /></a></div>
        <div class="profile-tab sticky"><div class="profile-card">
            <div class="profile-card-info">
              <a class="profile-card-avatar" href="/pic/pbs.twimg.com%2Fprofile_images%2F1648847697150103552%2FVbCybNN1.jpg" target="_blank"><img src="/pic/pbs.twimg.com%2Fprofile_images%2F1648847697150103552%2FVbCybNN1_400x400.jpg" alt="" loading="lazy" decoding="async" /></a>
              <div class="profile-card-tabs-name">
                <a class="profile-card-fullname" href="/GreatDismal" title="William Gibson">William Gibson</a>
                <a class="profile-card-username" href="/GreatDismal" title="@GreatDismal">@GreatDismal</a>
              </div>
            </div>
            <div class="profile-card-extra">
              <div class="profile-bio"><p dir="auto">Author of Neuromancer, The Peripheral, Agency… I’m also <a href="/greatdismal">@greatdismal</a>.bsky.social</p></div>
              <div class="profile-location">
                <span><div class="icon-container"><span class="icon-location" title=""></span></div></span>
                <span>Vancouver</span>
              </div>
              <div class="profile-website"><span>
                  <div class="icon-container"><span class="icon-link" title=""></span></div>
                  <a href="http://www.williamgibsonbooks.com">williamgibsonbooks.com</a>
                </span></div>
              <div class="profile-joindate"><span title="4:17 AM - 1 Apr 2009"><div class="icon-container"><span class="icon-calendar" title=""></span> Joined April 2009</div></span></div>
              <div class="profile-card-extra-links"><ul class="profile-statlist">
                  <li class="posts">
                    <span class="profile-stat-header">Tweets</span>
                    <span class="profile-stat-num">220,160</span>
                  </li>
                  <li class="following">
                    <span class="profile-stat-header">Following</span>
                    <span class="profile-stat-num">290</span>
                  </li>
                  <li class="followers">
                    <span class="profile-stat-header">Followers</span>
                    <span class="profile-stat-num">289,949</span>
                  </li>
                  <li class="likes">
                    <span class="profile-stat-header">Likes</span>
                    <span class="profile-stat-num">4,103</span>
                  </li>
                </ul></div>
            </div>
          </div></div>
        <div class="timeline-container">
          <ul class="tab">
            <li class="tab-item active"><a href="/GreatDismal">Tweets</a></li>
            <li class="tab-item wide"><a href="/GreatDismal/with_replies">Tweets &amp; Replies</a></li>
            <li class="tab-item"><a href="/GreatDismal/media">Media</a></li>
            <li class="tab-item"><a href="/GreatDismal/search">Search</a></li>
          </ul>
          <div class="timeline"><div class="timeline-header"><h2 class="timeline-none">No items found</h2></div></div>
        </div>
      </div></div>
  </body>
</html>`

**Comment by louisgrasset** [comment] 2023-06-30 09:27
Twitter currently blocks all signed-out users from accessing content

**Comment by zoubidabida** [comment] 2023-06-30 09:55
Oh ok. Thanks. 
Is there a way to configure nitter so it connects as a specific user ?

**Comment by Trit34** [comment] 2023-06-30 10:17
> Twitter currently blocks all signed-out users from accessing content

Probably another “bug” that could be fixed upstream, I guess…

But even with a logged-in Nitter instance, user search gives no results. Only tweets themselves are displayed.

**Comment by Xyncgas** [comment] 2023-06-30 12:12
Elon is not having freeloaders?

**Comment by zedeus** [comment] 2023-06-30 12:38
Not sure what's causing this issue, any errors in the logs? It's correct that user search is broken, there might not be a way to fix that if they took down the endpoint used.

**Comment by markcellus** [comment] 2023-06-30 12:44
Yeah this is definitely due to a recent change on Twitter's end. It appears they made a change that returns empty data in all of the Graph QL API responses. So you likely wouldnt see any error in the logs.

**Comment by kabiiQ** [comment] 2023-06-30 14:09
Any idea how some instances are still (partially, with_replies is definitely gone for everyone) working? Mine and some others are completely empty, but nitter.net and half the others I tried still provide regular Tweets.

**Comment by BANKA2017** [comment] 2023-06-30 14:27
I was running a crawler (UserTweets) and received such error all day yesterday, but today everything works fine again.

**Comment by cooljeanius** [comment] 2023-06-30 18:07
> Any idea how some instances are still (partially, with_replies is definitely gone for everyone) working? Mine and some others are completely empty, but nitter.net and half the others I tried still provide regular Tweets.

time for an additional column on the wiki page of instances for which instances are affected or not?

**Comment by santorfo** [comment] 2023-06-30 19:03
> Any idea how some instances are still (partially, with_replies is definitely gone for everyone) working? Mine and some others are completely empty, but nitter.net and half the others I tried still provide regular Tweets.

I get nothing on nitter.net

**Comment by unixfox** [comment] 2023-06-30 19:27
note: it's still possible to view tweets and more on the android app so I guess this is the last possible way to gain the access back without an account.

**Comment by xaur** [comment] 2023-06-30 19:42
Is it time to join all Nitter instances in a mesh that serves tweets regardless of Twitter? :)

**Comment by rorgoroth** [comment] 2023-06-30 19:50
> note: it's still possible to view tweets and more on the android app so I guess this is the last possible way to gain the access back without an account.

They'll probably "update" that app soon™ enough.

**Comment by unixfox** [comment] 2023-06-30 19:57
https://twitter.com/AqueelMiq/status/1674843555486134272

<img src="https://user-images.githubusercontent.com/4016501/250187077-45f65d3a-33dd-4e73-8ee2-574d909d0747.png" width="300" />

Like discussed [on matrix](https://matrix.to/#/#nitter:matrix.org) it's probably temporary.

**Comment by sunlightspectre** [comment] 2023-06-30 19:58
@unixfox Though I don't disagree it's temporary _now,_ the fact a company can inevitably becomes a company _doing_ a thing, regardless of how asinine it is. It's basically a straight line from 'dumb idea' to 'terrible implementation.'

We shall believe it when we see it.

**Comment by cooljeanius** [comment] 2023-06-30 20:06
> Like discussed [on matrix](https://matrix.to/#/#nitter:matrix.org) it's probably temporary.

OK, but what if it isn't?

**Comment by unixfox** [comment] 2023-06-30 20:13
update: https://twitter.com/elonmusk/status/1674865731136020505

> elon says: "Temporary emergency measure. We were getting data pillaged so much that it was degrading service for normal users!"

**Comment by mpeter50** [comment] 2023-06-30 22:55
I suspect that if and by the time they undo this restriction, they will have some sort of anti-bot protection.

**Comment by zedeus** [comment] 2023-07-01 20:06
Duplicate of #919

**Closed by zedeus** 2023-07-01 20:06 UTC
