### ISSUE TITLE
DMCA and some b*llsh1t

### ISSUE THREAD

**Issue by D3vl0per** [zedeus/nitter#482] opened 2021-12-18 20:31 UTC
Dear fellow nitter instance operators,

I have received a few DMCA claims recently, what have I do?
How can I explain to the d3g3n3r4t3s that I didn't steal their jobs and their entire lives, because it's just a proxy?

That was the first one(she is work in the adult entertainment industry lol):
![dmca-nitter](https://user-images.githubusercontent.com/34040149/146654666-52ea1423-7e77-4ef1-b5e8-6cc7f5d4c7b1.png)
And the second one:
![dmca-nitter2](https://user-images.githubusercontent.com/34040149/146654667-825193a6-b9c6-4593-9310-4da2a3c49886.png)

Ms. L. (the second one) have a small NFT collection btw. Would it be annoyed if I screenshot of it? :laughing: 

But seriously, what do I do with these requests?

**Comment by datanomi** [comment] 2021-12-18 22:47
You should explain to your hosting provider that nitter does not store anything and is nothing more than a proxy.

**Comment by unixfox** [comment] 2021-12-19 11:31
Hey at invidious we also receive this kind of DMCA abuse and we created a template for that: https://github.com/iv-org/documentation/blob/master/Takedowns.md

**Comment by D3vl0per** [comment] 2021-12-19 14:09
@datanomi Thanks for the advice, I wrote to the provider.
I made a redirection, so the links in the request are not available now.

@unixfox I know the invidious project, I use it a lot :-). It would be useful to put a DMCA request option on the nitter instances.
Finally, I would like to pick out a snippet from Twitter's ToS (https://twitter.com/en/tos#intlTerms):

> By submitting, posting or displaying Content on or through the Services, you grant us a worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute such Content in any and all media or distribution methods now known or later developed (for clarity, these rights include, for example, curating, transforming, and translating). This license authorizes us to make your Content available to the rest of the world and to let others do the same.
This license authorizes us to make your Content available to the rest of the world and to let others do the same.

**Comment by zedeus** [comment] 2021-12-19 15:53
Good find @D3vl0per, I believe this line is the most relevant:
> This license authorizes us to make your Content available to the rest of the world and to *let others do the same*.

**Comment by D3vl0per** [comment] 2021-12-20 14:56
Ms. L. want to sue me about steal her copyrighted contents. She already won 2.4 million USD against thieves like me.

**Comment by TheFrenchGhosty** [comment] 2021-12-20 15:41
I received a message like that on December 12 (it wasn't a legal request so I just ghosted them), your instance was linked (mine wasn't for whatever reason), so I'm guessing it's from the same person:

(Note: the links are NSFW)

![nope](https://user-images.githubusercontent.com/47571719/146793349-02ebf52f-8f25-4a23-a10d-ca524e9c0b72.png)

**Comment by D3vl0per** [comment] 2021-12-20 16:00
> I received a message like that on December 12 (it wasn't a legal request so I just ghosted them), your instance was linked (mine wasn't for whatever reason), so I'm guessing it's from the same person:
> 
> (Note: the links are NSFW)
> 
> ![nope](https://user-images.githubusercontent.com/47571719/146793349-02ebf52f-8f25-4a23-a10d-ca524e9c0b72.png)

LOL, thanks for this information! I will add it to the blacklist.

**Comment by nipos** [comment] 2021-12-21 14:09
I received a similar complaint yesterday from my hoster.
They threatened to shut my whole server down if I don't respond within 24 hours.
I immediately shut the Nitter service down temporarily and answered to them, describing that Nitter is only a proxy and asked if I can offer that service again.
I haven't received a response yet, but that's a really difficult situation for me as I host much stuff on one single big dedicated server and hundreds of users trust me to provide a reliable service.
It would be much appreciated to have a clear statement whether Nitter is legal (in Germany) or not.

**Comment by unixfox** [comment] 2021-12-21 14:17
> I received a similar complaint yesterday from my hoster. They threatened to shut my whole server down if I don't respond within 24 hours. I immediately shut the Nitter service down temporarily and answered to them, describing that Nitter is only a proxy and asked if I can offer that service again. I haven't received a response yet, but that's a really difficult situation for me as I host much stuff on one single big dedicated server and hundreds of users trust me to provide a reliable service. It would be much appreciated to have a clear statement whether Nitter is legal (in Germany) or not.

I'm not a lawyer but Germany is in the European Union, and we published templates for Invidious stating inside it that Invidious (so is Nitter) fall under the directive 2001/29/EC of the European Parliament

**Comment by TheFrenchGhosty** [comment] 2021-12-21 14:18
@nipos 

Just adjust our UE template for Nitter, and send that to your hosting provider: https://github.com/iv-org/documentation/blob/master/Takedowns.md

**Comment by nipos** [comment] 2021-12-21 14:25
I can send that right to the copyright trolls, thank you.
The hoster wanted that the problem is solved (translate that to: content removed) and take action to prevent that from happening again and also a statement how that could happen and what I've done, so I think that letter would not have been enough.

**Comment by TheFrenchGhosty** [comment] 2021-12-21 14:29
@nipos Unless you have a really crappy hosting provider, this letter is enough.

**Comment by nipos** [comment] 2021-12-21 14:34
I don't think Hetzner is that crappy, the message was just very scary...
Well, let's wait what they'll respond as I already sent something yesterday.

**Comment by TheFrenchGhosty** [comment] 2021-12-21 14:36
@nipos If you send a proper explanation to Hetzner they will side with you, Nitter is 100% legal.

**Comment by utzer** [comment] 2021-12-21 16:13
> @unixfox I know the invidious project, I use it a lot :-). It would be useful to put a DMCA request option on the nitter instances.
> Finally, I would like to pick out a snippet from Twitter's ToS (https://twitter.com/en/tos#intlTerms):

yes, or at least some contact option, I asked for this a long time ago in some issue I think. I Germany you need to have some kind of "imprint", which I don't like much, but would still like to have a option for that. 
Maybe just add the possibility to add some impress.html somehow which includes the body (unformated html) or some contact page that can contain contact details of whatever. That would be so great. Or some setting to at least be able to add some link with a variable name on the page, which is the requirement by law in Germany, there must be "Impressum" or "Kontakt" or something like this reachable from any page, which almost no open source project does. 

Is there some easy way to add such a DMCA/contact/imprint page or even a link? @zedeus?

**Comment by D3vl0per** [comment] 2021-12-21 22:14
I got a response from Hetzner. They can't find these requests LOL.
![image](https://user-images.githubusercontent.com/34040149/147004527-aac39fae-11d1-40e3-bc54-9894a7c0c5ab.jpeg)

**Comment by D3vl0per** [comment] 2021-12-21 22:18
> I received a similar complaint yesterday from my hoster.
> 
> They threatened to shut my whole server down if I don't respond within 24 hours.
> 
> I immediately shut the Nitter service down temporarily and answered to them, describing that Nitter is only a proxy and asked if I can offer that service again.
> 
> I haven't received a response yet, but that's a really difficult situation for me as I host much stuff on one single big dedicated server and hundreds of users trust me to provide a reliable service.
> 
> It would be much appreciated to have a clear statement whether Nitter is legal (in Germany) or not.

Just block the requested url path while this request is pending. I did the same.

**Comment by nipos** [comment] 2022-01-02 11:00
I still haven't received any response from Hetzner.
Can I enable the Nitter service again or do I risk losing my server?
What happens if they receive a similar DMCA complaint again,can they remove the server without any warning then or can I still shutdown the Nitter service then?

**Comment by xnaas** [comment] 2022-01-03 14:52
FWIW, whoever runs [nixnet.services](https://nixnet.services/) looks like the got tired of being DMCA trolled: https://nixnet.services/blog/nitter-behind-http-basic-auth/ – super unfortunate thing to see happen. ☹️

**Comment by D3vl0per** [comment] 2022-01-04 01:33
Sorry, but I don't understand.
What is the difference between a very known password protected access and the no password option?
(Of course in legal terms.)

**Comment by xnaas** [comment] 2022-01-04 01:41
I imagine that it immediately stops the presumably automated DMCA spam. I'm not the owner of the site, so can't say if it helped. ¯\\\_(ツ)_/¯

**Comment by nipos** [comment] 2022-01-04 09:03
I think I'll try the same solution,looks good to me.
It makes it a bit more difficult for the users,but still better than shutting down the service completely.
And I have zero interest in dealing with this DMCA bullshit permanently.

**Comment by zedeus** [comment] 2022-01-04 09:35
> What happens if they receive a similar DMCA complaint again

Then the process starts over. As long as you send a response to each dispute, e.g. using the template provided here, you should be fine.

**Comment by unixfox** [comment] 2022-01-04 09:48
The best idea would be to have in front of your nitter server, a server from a hosting provider that don't care about DMCA requests.

**Comment by nocturn9x** [comment] 2022-01-04 14:05
I'm gonna try hosting an invidious and nitter instance. As soon as I receive DMCA complaints I'll work on a bot that automatically parses those emails and replies with the formatted answer.

Gonna be fun

**Comment by TheFrenchGhosty** [comment] 2022-01-06 18:09
I just received a request from a US law firm.

![nitter](https://user-images.githubusercontent.com/47571719/148429792-98ac8dff-4376-4915-a4fa-545dbdb4f782.png)

They mention that they already contacted me once (but they didn't), I'll answer with the template I sent before (and not ghost them since this isn't just a random user).

**Comment by zedeus** [comment] 2022-01-10 12:04
I just got another abuse message from Hetzner for nitter.net and responded using @TheFrenchGhosty's template. I'll post an update when Hetzner does something, hopefully just closing the ticket.

**Comment by D3vl0per** [comment] 2022-01-12 16:57
@zedeus https://nitter.hu/Hetzner_Online/status/1481245111027699716

**Comment by zedeus** [comment] 2022-01-12 17:14
Very nice, she even told us to just use a template, so everything is good. I haven't received any response and nitter.net is still up, so I'm assuming they just closed the ticket.

**Comment by zedeus** [comment] 2022-01-15 02:25
I still haven't heard from Hetzner, so I dunno if they closed the ticket or haven't processed my response yet.
I've created a wiki page for the DMCA template that also links to this issue, but there has been plenty of discussion and I think the consensus now is to just throw the template back at them, especially with Hetzner's message about doing so.
https://github.com/zedeus/nitter/wiki/DMCA-template

**Closed by zedeus** 2022-01-15 02:25 UTC
Labels: discussion

**Comment by TheFrenchGhosty** [comment] 2022-01-15 17:28
@zedeus Just FYI, this is a template specific to the EU, it doesn't apply to the US, you need 1 template for the EU, and for the US: https://docs.invidious.io/en/Takedowns

**Comment by zedeus** [comment] 2022-01-15 18:23
Noted, thank you. Added two separate templates.

**Comment by TheFrenchGhosty** [comment] 2022-03-04 14:13
DMCA received (it's invalid, but I'll still contest it).

![1](https://user-images.githubusercontent.com/47571719/156778750-89fc31e3-e80a-4362-ae2a-20bc0baa8292.png)
![2](https://user-images.githubusercontent.com/47571719/156778764-72a78eb9-f998-49b1-b4cc-497bc5ce848d.png)

**Comment by utzer** [comment] 2022-05-10 08:50
Hey @zedeus yesterday I was asked by Hetzner to take down nitter.eu, they stated copyright and tos 8.2 (AGB for Germany) to be violated. 
Did you ever have the abuse team contact you about something like this? They stumbled upon nitter.eu because of some illegal stuff on twitter.com which nitter.eu made accessible. 
I now HTTP 307 the .eu to .net, as I don't want to break all links everywhere, I can switch it so some other instace in case you get too much load from that forward.

**Comment by zedeus** [comment] 2022-05-10 09:45
@utzer Yes, Hetzner very recently told me to take down nitter.net after I argued with their corporate lawyer over the bogus takedown requests and their misundestanding of both copyright law and their own ToS. I've since moved it to a different provider.

**Comment by nocturn9x** [comment] 2022-05-10 09:48
> @utzer Yes, Hetzner very recently told me to take down nitter.net after I argued with their corporate lawyer over the bogus takedown requests and their misundestanding of both copyright law and their own ToS. I've since moved it to a different provider. Redirecting is fine, but could you use a different instance for the time being? We're trying to figure out some intermittent SSL errors on the new server, so it would be nice to get that done first.

I even got banned because of the same reason (breaking point 8.2 of ToS), and without notice unlike you. I moved to much more sane providers now. Quite frankly, I hope Hetzner's legal department burns in hell

**Comment by utzer** [comment] 2022-05-10 21:12
@nocturn9x I don't like OVH very much, but I think at some point I will split up my services to different providers. And thanks, I will set [nitter.nocturn9x.space](https://nitter.nocturn9x.space/).

**Comment by nocturn9x** [comment] 2022-05-10 21:15
> @nocturn9x I don't like OVH very much, but I think at some point I will split up my services to different providers. And thanks, I will set [nitter.nocturn9x.space](https://nitter.nocturn9x.space/).

It's an OVH reseller. They're pretty neat, great support and bang up prices

**Comment by utzer** [comment] 2022-05-10 21:15
@nocturn9x sorry... updated above reply.

**Comment by nocturn9x** [comment] 2022-05-10 21:16
> @nocturn9x sorry... updated above reply. 

Hm, weird. I think there's a bug with the redis implementation nim is using. I'll have to see if I can fix that

**Comment by datanomi** [comment] 2022-05-10 21:34
You can use my instance nitter.it although it's hosted on hetzner :D
