### ISSUE TITLE
nitter.net has disappeared

### ISSUE THREAD

**Issue by thutt** [zedeus/nitter#1150] opened 2024-01-14 00:45 UTC
This isn't an issue with nitter software, but I'm getting the following:

  Hmm. We’re having trouble finding that site.  
  We can’t connect to the server at nitter.net.

When attempting to navigate to Twitter's user pages via nitter.net.

Comparatively, has the DNS registration disappeared?  (The registration is valid until 2024.08.06, according to a whois lookup)

nslookup twitter.com

Non-authoritative answer:
Name:   twitter.com
Address: 104.244.42.65
Name:   twitter.com
Address: 104.244.42.1
Name:   twitter.com
Address: 104.244.42.129
Name:   twitter.com
Address: 104.244.42.193

nslookup nitter.net

Non-authoritative answer:
*** Can't find nitter.net: No answer

**Comment by zedeus** [comment] 2024-01-14 01:09
nitter.net is unavailable because Njalla (domain vendor) suspended my account. I'm waiting for them to respond.

**Comment by awsms** [comment] 2024-01-14 01:10
> nitter.net is unavailable because Njalla (domain vendor) suspended my account. I'm waiting for them to respond.

Thx for the quick answer, I was a bit worried as the website hasn't been available for the whole day

**Comment by gigirassy** [comment] 2024-01-14 01:15
Hope this gets resolved!

**Comment by stopmotio** [comment] 2024-01-14 01:19
Any idea as to why they may have done that?

**Comment by lukefromdc** [comment] 2024-01-14 02:19
We need to know if Twitter is whining to domain vendors about Nitter instances.

**Comment by retry-the-user** [comment] 2024-01-14 02:21
in the meantime add 185.246.188.57 nitter.net to your hosts file and you can still use it

**Comment by lukefromdc** [comment] 2024-01-14 02:23
That gets a login request on an otherwise blank/white page

**Comment by jrfondren** [comment] 2024-01-14 02:28
That IP works. You can't, however, go to https://$ip/ as that'll cause your browser to send the IP in the Host: header, which means the server won't dispatch the request to nitter.net. You need to do something like add it to your hosts file.

**Comment by retry-the-user** [comment] 2024-01-14 02:29
Do you people not read? "in the meantime **add 185.246.188.57 nitter.net to your hosts file and you can still use it**"

add
to your hosts file

**Comment by jrfondren** [comment] 2024-01-14 02:33
Someone without a relatively thorough understanding of webhosting will go to https://$ip/, get an error, and then conclude that the IP is wrong. Since the IP is wrong, why go to the effort of modifying a hosts file to something wrong?

Anything related to name resolution you'll just have to explain three times.

**Comment by stopmotio** [comment] 2024-01-14 03:00
I was about to try the raw IP itself lol

**Comment by lukefromdc** [comment] 2024-01-14 03:08
When using DNS over HTTPS in Firefox, /etc/hosts is ignored by the browser. I consider this
a nuisance side effect of forcing any ISP surveillance to use raw IP addresses and look them
up themselves (which automated snooping may not bother with) as it makes blocking things
like Facebook, Google, and their embedded content more difficult.

**Comment by lukefromdc** [comment] 2024-01-14 03:15
How do I stop Firefox from redirecting 185.246.188.57 to https://185.246.188.57 with DNS over https engaged?

Webhosting I know little about, BTW.

**Comment by jrfondren** [comment] 2024-01-14 03:34
1. use another nitter instance that's still up
2. use another browser that the hosts file works for (Brave is one)
3. use your own DNS server and change your router or your computer to use it. A DNS server is a likely component of anti-adware solutions that work outside the browser, like a pihole.
4. use a public/alternate DNS service that supports edits (I don't know of any)
5. clone nitter, add in a new feature to have it proxy requests to an existing nitter server, plug the IP into that, and then make a pull request to add this as a normal feature. This way people can hit localhost without having to duplicate the elaborate auth system that's required now.

**Comment by stopmotio** [comment] 2024-01-14 03:49
Just disable DNS over HTTPS and give it another go

**Comment by jarrodmoldrich** [comment] 2024-01-14 03:49
@lukefromdc In Firefox, I believe you can set `network.trr.exclude-etc-hosts` to `true` in `about:config`.  You may have to add the relevant domains to `network.trr.excluded-domains` also, but I didn't need to.

**Comment by abhranil26** [comment] 2024-01-14 04:51
Yeah added to hosts file on macos, and seems to be working with Chrome

**Comment by zedeus** [comment] 2024-01-14 05:21
@lukefromdc @stopmotio someone filed a complaint to Njalla about unconsensual nudity being hosted on nitter.net, with a link that actually came from another instance. It's the first time I've ever gotten any semblance of a takedown request via Njalla, so I didn't think much of it when I got an email with the subject "Njalla: New Message", and the body just being a link, while traveling. A couple days later and one more email, they just suspended the account, which I only found out because nitter.net became unreachable.

**Comment by zedeus** [comment] 2024-01-14 05:40
These are the two emails I received prior to suspension:
![Screenshot_2024-01-14-05-32-26-26_c3025e5ce50ffdc2876b487a5468618d](https://github.com/zedeus/nitter/assets/9434921/50d14c5d-cf93-4d77-9a58-70007d68fde6)
![Screenshot_2024-01-14-05-32-42-93_c3025e5ce50ffdc2876b487a5468618d](https://github.com/zedeus/nitter/assets/9434921/160a5ab5-2a32-4b00-9c08-60fd12e0da2a)

Hetzner at least included plenty of information about the urgency and the full report information, until they gave up and suspended my account.

Njalla's handling of this is amateurish at best. Here's the actual support message:
![IMG_20240114_053654_338](https://github.com/zedeus/nitter/assets/9434921/a11a81eb-28e0-471e-baf2-03cba04d9f72)

A funny thing to note here is that the image link, which first points at nitter.it, is a /enc/ link which only gets created by Nitter if the instance admin enables base64 link encoding for media proxying. This is not enabled for nitter.net, so I know for a fact someone copied an image from another instance (presumably nitter.it), changed the domain, and sent a complaint to Njalla.

**Comment by lukefromdc** [comment] 2024-01-14 06:04
> @lukefromdc @stopmotio someone filed a complaint to Njalla about unconsensual nudity being hosted on nitter.net, with a link that actually came from another instance. It's the first time I've ever gotten any semblance of a takedown request via Njalla, so I didn't think much of it when I got an email with the subject "Njalla: New Message", and the body just being a link, while traveling. A couple days later and one more email, they just suspended the account. I only found out when nitter.net became unreachable.

That means they suspended your account without properly investigating the account. Whoever set this up could potentially be working for Elon Musk

**Comment by lukefromdc** [comment] 2024-01-14 06:14
https://nitter.it/ does seem to be working, though you do have to click through an expired certificate warning. Given what Nitter is used for, I am assuming TWITTER is the host of any nonconsensual nudity found via any nitter instance.

**Comment by abacabadabacaba** [comment] 2024-01-14 06:36
It's really funny that people here and on Hacker News hypothesize that Twitter is behind this. In fact, Twitter couldn't care less. If they did, they won't bother sending takedown requests, they would just block Nitter on their end, which should be easier for them and which is something they are entirely in their right to do.
If you read TorrentFreak, you would know what a mess the situation with takedown requests is. That people receive requests to remove nonexistent URLs, or URLs on websites they have nothing to do with, is completely par for the course.

**Comment by justinclift** [comment] 2024-01-14 06:41
@zedeus Might be time to create some backup domain names?

Wonder if it's also useful to use a registrar that doesn't roll over to random takedown requests too?  (easydns.com springs to mind, but there are probably others)

**Comment by Sketch6307** [comment] 2024-01-14 08:04
> It's really funny that people here and on Hacker News hypothesize that Twitter is behind this. In fact, Twitter couldn't care less. If they did, they won't bother sending takedown requests, they would just block Nitter on their end, which should be easier for them and which is something they are entirely in their right to do. If you read TorrentFreak, you would know what a mess the situation with takedown requests is. That people receive requests to remove nonexistent URLs, or URLs on websites they have nothing to do with, is completely par for the course.

They've tried repeatedly to block nitter 🤣 if you don't know what you're talking about then don't talk

**Comment by Apachez-** [comment] 2024-01-14 08:18
> It's really funny that people here and on Hacker News hypothesize that Twitter is behind this. In fact, Twitter couldn't care less. If they did, they won't bother sending takedown requests, they would just block Nitter on their end, which should be easier for them and which is something they are entirely in their right to do. If you read TorrentFreak, you would know what a mess the situation with takedown requests is. That people receive requests to remove nonexistent URLs, or URLs on websites they have nothing to do with, is completely par for the course.

Twitter cares since Nitter is growing and making Twitter losing ad revenue and also losing possibility for Twitter to merge statistics with other sources and sell your information to others.

But going from these facts into some conspiracy theory that Elon Musk himself have an evil plot on how to shutdown Nitter well... is a bit far fetch to say the least. Could simply be verified if the URLs in question works when going directly to Twitter or not. If they are blocked going through x.com but not when proxied through Nitter (unless some cache at Nitter) then we can turn the conspiracy theory into a reality.

Workaround is to pick another mirror for now:

https://status.d420.de/

Other status for when the downtime started (depending on timezone in the night between saturday and sunday 13-14 january 2024):

https://updownradar.com/status/nitter.net

Regarding the domain itself what should be fixed is to use a:

- Proper registrar.
- Proper DNS-server hosting.
- Proper web-server hosting.

That is vendors who doesnt shit bricks due to some complaints but rather find out whats really going on and in this case the solution would probably have been to let nitter.net refresh its caches (for the case where the URLs have already been removed at the source which is Twitter/X) or if needed add these URLs to a blacklist in case Twitter itself dont block these.

**Comment by Apachez-** [comment] 2024-01-14 08:18
> @zedeus Might be time to create some backup domain names?
> 
> Wonder if it's also useful to use a registrar that doesn't roll over to random takedown requests too? (easydns.com springs to mind, but there are probably others)

Already exists, take a look at https://status.d420.de/ for mirrors and their status.

**Comment by animegrafmays** [comment] 2024-01-14 08:36
> Regarding the domain itself what should be fixed is to use a:
> 
>     * Proper registrar.
> 
>     * Proper DNS-server hosting.
> 
>     * Proper web-server hosting.
> 
> 
> That is vendors who doesnt shit bricks due to some complaints but rather find out whats really going on and in this case the solution would probably have been to let nitter.net refresh its caches (for the case where the URLs have already been removed at the source which is Twitter/X) or if needed add these URLs to a blacklist in case Twitter itself dont block these.

welcome to 2024. political pressure will make any of them snap. there is no such thing as a 'proper registrar' anymore. njal.la is just a proxy (we use them too but I'm definitely moving after this). we use porkbun which has been stable and in the event a friend had his domain taken they were not at fault and tried to help him recover it. epik was okay until they had their entire database leaked.

this is the same issue people right of center politically speaking have been fighting for the last 7 years. the walls are closing in on any and everything and it's only going to get worse from here

**Comment by abacabadabacaba** [comment] 2024-01-14 09:03
> They've tried repeatedly to block nitter 🤣 if you don't know what you're talking about then don't talk

If I worked at Twitter and my task were to block Nitter, the first thing I would do is to write a script that gets IPs of all Nitter instances, and adds them to a block list. The second, if Nitter started using proxies, would be to make a script that requests a random nonexistent ID through every instance, and block all IPs that happen to request the same ID from Twitter. Since Twitter hasn't done any of this, I conclude that they aren't really trying to block Nitter.

**Comment by nayr7** [comment] 2024-01-14 10:56
Just yet another instance of why you should never use njalla.

**Comment by barelyprofessional** [comment] 2024-01-14 11:34
njal.la reversed their idiotic decision?

```
nitter.net.             3600    IN      A       185.246.188.57
nitter.net.             36000   IN      NS      3-get.njalla.fo.
nitter.net.             36000   IN      NS      1-you.njalla.no.
nitter.net.             36000   IN      NS      2-can.njalla.in.
;; Received 170 bytes from 185.193.124.34#53(2-can.njalla.in) in 48 ms
```

I suppose they realized this might tarnish their reputation a bit. I'm still blown away that people recommend their lousy service as they do things like this time after time.

If the domain has been unblocked, please consider transferring to literally anyone else.

**Comment by zaee-k** [comment] 2024-01-14 11:39
> njal.la reversed their idiotic decision?
> 
> ```
> nitter.net.             3600    IN      A       185.246.188.57
> nitter.net.             36000   IN      NS      3-get.njalla.fo.
> nitter.net.             36000   IN      NS      1-you.njalla.no.
> nitter.net.             36000   IN      NS      2-can.njalla.in.
> ;; Received 170 bytes from 185.193.124.34#53(2-can.njalla.in) in 48 ms
> ```
> 
> I suppose they realized this might tarnish their reputation a bit. I'm still blown away that people recommend their lousy service as they do things like this time after time.
> 
> If the domain has been unblocked, please consider transferring to literally anyone else.

Is there any alternative register which treats privacy and handles stuff more professionally than njalla?

**Comment by animegrafmays** [comment] 2024-01-14 11:52
> > njal.la reversed their idiotic decision?
> > ```
> > nitter.net.             3600    IN      A       185.246.188.57
> > nitter.net.             36000   IN      NS      3-get.njalla.fo.
> > nitter.net.             36000   IN      NS      1-you.njalla.no.
> > nitter.net.             36000   IN      NS      2-can.njalla.in.
> > ;; Received 170 bytes from 185.193.124.34#53(2-can.njalla.in) in 48 ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I suppose they realized this might tarnish their reputation a bit. I'm still blown away that people recommend their lousy service as they do things like this time after time.
> > If the domain has been unblocked, please consider transferring to literally anyone else.
> 
> Is there any alternative register which treats privacy and handles stuff more professionally than njalla?

njalla isn't a registrar, njalla is a proxy. in this case njalla proxied a registration for nitter.net via Tucows. so Tucows was the registrar. 99.9999999% of the time njalla doesn't care about reports because they never make it to njalla.  this  time it did, because it was Tucows. and because they didnt receive a response they locked his account because the alternative is Tucows stops allowing them to proxy for third party users.

**Comment by barelyprofessional** [comment] 2024-01-14 12:15
> > njal.la reversed their idiotic decision?
> > ```
> > nitter.net.             3600    IN      A       185.246.188.57
> > nitter.net.             36000   IN      NS      3-get.njalla.fo.
> > nitter.net.             36000   IN      NS      1-you.njalla.no.
> > nitter.net.             36000   IN      NS      2-can.njalla.in.
> > ;; Received 170 bytes from 185.193.124.34#53(2-can.njalla.in) in 48 ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I suppose they realized this might tarnish their reputation a bit. I'm still blown away that people recommend their lousy service as they do things like this time after time.
> > If the domain has been unblocked, please consider transferring to literally anyone else.
> 
> Is there any alternative register which treats privacy and handles stuff more professionally than njalla?

Maybe Incognet, but I don't have personal experience with their service, just it's well regarded by @jaw-sh and he's got a lot of experience with hosting websites people don't like.

You'll have issues with anyone who is reselling to anonymous registrants though, they take on more burden than the typical registrar. For most people, any accredited registrar is fine, though personally I like Porkbun as their pricing is good and they support hardware tokens for 2FA.

One to look out for in the future is NameCrane, which is still "Coming Soon", but will be an ICANN accredited registrar operated by Francisco of BuyVM. He's a good guy, but you'll still have to give over your personal information per ICANN.

> > > njal.la reversed their idiotic decision?
> > > ```
> > > nitter.net.             3600    IN      A       185.246.188.57
> > > nitter.net.             36000   IN      NS      3-get.njalla.fo.
> > > nitter.net.             36000   IN      NS      1-you.njalla.no.
> > > nitter.net.             36000   IN      NS      2-can.njalla.in.
> > > ;; Received 170 bytes from 185.193.124.34#53(2-can.njalla.in) in 48 ms
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I suppose they realized this might tarnish their reputation a bit. I'm still blown away that people recommend their lousy service as they do things like this time after time.
> > > If the domain has been unblocked, please consider transferring to literally anyone else.
> > 
> > 
> > Is there any alternative register which treats privacy and handles stuff more professionally than njalla?
> 
> njalla isn't a registrar, njalla is a proxy. in this case njalla proxied a registration for nitter.net via Tucows. so Tucows was the registrar. 99.9999999% of the time njalla doesn't care about reports because they never make it to njalla. this time it did, because it was Tucows. and because they didnt receive a response they locked his account because the alternative is Tucows stops allowing them to proxy for third party users.

Considering nitter.net has its nameservers delegated to Njalla, it doesn't take a genius to work out its registered to Njalla, skip Tucows and complain directly. I don't see anything that says whether it was Tucows or somebody complaining to Njalla directly.

**Comment by animegrafmays** [comment] 2024-01-14 12:17
> Considering nitter.net has its nameservers delegated to Njalla, it doesn't take a genius to work out its registered to Njalla, skip Tucows and complain directly. I don't see anything that says whether it was Tucows or somebody complaining to Njalla directly.


```
$ whois nitter.net
[...]
Registrar Abuse Contact Email: domainabuse@tucows.com
Registrar Abuse Contact Phone: +1.4165350123
```

lrn2dns

**Comment by justinclift** [comment] 2024-01-14 12:31
> Is there any alternative register which treats privacy and handles stuff more professionally than njalla?

EasyDNS (easydns.com).  We (sqlitebrowser.org) use them, and for us they've been pretty good.

We're not really a target for abuse though, or at least we haven't been until now. :sweat_smile:

**Comment by barelyprofessional** [comment] 2024-01-14 12:38
> > Considering nitter.net has its nameservers delegated to Njalla, it doesn't take a genius to work out its registered to Njalla, skip Tucows and complain directly. I don't see anything that says whether it was Tucows or somebody complaining to Njalla directly.
> 
> ```
> $ whois nitter.net
> [...]
> Registrar Abuse Contact Email: domainabuse@tucows.com
> Registrar Abuse Contact Phone: +1.4165350123
> ```
> 
> lrn2dns

Learn to read
```
Name Server: 1-you.njalla.no
Name Server: 2-can.njalla.in
Name Server: 3-get.njalla.fo
```

If I want to take a domain down, why would I bother with the registrar when the registrant has been revealed to be a trigger happy reseller? All I'm saying is that you don't know Tucows was involved for certain.

I remember a while ago you were talking about becoming ICANN accredited for Poast. Whatever happened to that? Lost all the required money getting drunk while screaming at your users? I'm praying for your liver.

**Comment by zedeus** [comment] 2024-01-14 12:38
Here's the super professional reply by Njalla:
![Screenshot_2024-01-14-12-35-45-54_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/zedeus/nitter/assets/9434921/eb0927db-15f5-4ce7-bdda-d0b1d8f6996d)

My response:
![Screenshot_2024-01-14-12-37-11-35_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/zedeus/nitter/assets/9434921/23a5dc3d-6577-40fe-80f9-d6492e75ec5e)

**Comment by animegrafmays** [comment] 2024-01-14 12:40
> > > Considering nitter.net has its nameservers delegated to Njalla, it doesn't take a genius to work out its registered to Njalla, skip Tucows and complain directly. I don't see anything that says whether it was Tucows or somebody complaining to Njalla directly.
> > 
> > 
> > ```
> > $ whois nitter.net
> > [...]
> > Registrar Abuse Contact Email: domainabuse@tucows.com
> > Registrar Abuse Contact Phone: +1.4165350123
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > lrn2dns
> 
> Learn to read
> 
> ```
> Name Server: 1-you.njalla.no
> Name Server: 2-can.njalla.in
> Name Server: 3-get.njalla.fo
> ```
> 
> If I want to take a domain down, why would I bother with the registrar when the registrant has been revealed to be a trigger happy reseller? All I'm saying is that you don't know Tucows was involved for certain.
> 
> I remember a while ago you were talking about becoming ICANN accredited for Poast. Whatever happened to that? Lost all the required money getting drunk while screaming at your users? I'm praying for your liver.

using a public issue to try to attack me, go back to kiwifarms. there's a reason nobody wants to deal with josh and his users and you are doing nothing but proving that right

**Comment by animegrafmays** [comment] 2024-01-14 13:10
> Here's the super professional reply by Njalla: ![Screenshot_2024-01-14-12-35-45-54_e4424258c8b8649f6e67d283a50a2cbc](https://private-user-images.githubusercontent.com/9434921/296550075-eb0927db-15f5-4ce7-bdda-d0b1d8f6996d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzgwOTksIm5iZiI6MTcwNTIzNzc5OSwicGF0aCI6Ii85NDM0OTIxLzI5NjU1MDA3NS1lYjA5MjdkYi0xNWY1LTRjZTctYmRkYS1kMGIxZDhmNjk5NmQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTMwOTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM1YmY2ZDc0NjU4OGY4OTYwOWI2YWZlYmQ4MTMxY2Q0ZDY5MjJlOGQyODk5YmJiZmFlZDgyNDk0MTIzYzU0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZX48UskQTTYpBotdK0_beAKfKjKD2dGj0IJnYIe7SVQ)
> 
> My response: ![Screenshot_2024-01-14-12-37-11-35_e4424258c8b8649f6e67d283a50a2cbc](https://private-user-images.githubusercontent.com/9434921/296550066-23a5dc3d-6577-40fe-80f9-d6492e75ec5e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzgwOTksIm5iZiI6MTcwNTIzNzc5OSwicGF0aCI6Ii85NDM0OTIxLzI5NjU1MDA2Ni0yM2E1ZGMzZC02NTc3LTQwZmUtODBmOS1kNjQ5MmU3NWVjNWUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTMwOTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhkMDAwYWUxODk0NzgxNjYyNzZkMjA5MzY3MjJjZGU4MjcyNGE3M2RlMDM2ODk2ZTRhMTk3M2M5ZTIyYjE4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZKD_nV90Y3tKY_6mdZbl51jVybpe7byRrjJMFP8A_Js)

you can ask them for the official complaint presented to tucows. did they not forward it to you?

**Comment by zedeus** [comment] 2024-01-14 13:12
No official complaint has been forwarded, this is all I got: https://github.com/zedeus/nitter/issues/1150#issuecomment-1890855255

**Comment by animegrafmays** [comment] 2024-01-14 13:14
if they wont give you the actual complaint and would suspend you instead I would migrate off. on fedi we have all had good results with porkbun. I will be moving our domains off njalla today because of this

**Comment by DeeDotNET** [comment] 2024-01-14 13:19
![image](https://github.com/zedeus/nitter/assets/138911215/f6b0165c-4e8e-42bc-a9ff-ee2a0d15d1cd)
seems like the site's back online as of now

**Comment by IdfbAn** [comment] 2024-01-14 13:25
It's back! (for now)

**Comment by Apachez-** [comment] 2024-01-14 13:40
> > Regarding the domain itself what should be fixed is to use a:
> > ```
> > * Proper registrar.
> > 
> > * Proper DNS-server hosting.
> > 
> > * Proper web-server hosting.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That is vendors who doesnt shit bricks due to some complaints but rather find out whats really going on and in this case the solution would probably have been to let nitter.net refresh its caches (for the case where the URLs have already been removed at the source which is Twitter/X) or if needed add these URLs to a blacklist in case Twitter itself dont block these.
> 
> welcome to 2024. political pressure will make any of them snap. there is no such thing as a 'proper registrar' anymore. njal.la is just a proxy (we use them too but I'm definitely moving after this). we use porkbun which has been stable and in the event a friend had his domain taken they were not at fault and tried to help him recover it. epik was okay until they had their entire database leaked.
> 
> this is the same issue people right of center politically speaking have been fighting for the last 7 years. the walls are closing in on any and everything and it's only going to get worse from here

Then you will unfortunately have to look at how others does this.

For example Piratebay seems to currently use Namebright as registrar.

**Comment by animegrafmays** [comment] 2024-01-14 13:47
again, njalla is a proxy. njalla registers (or maintains registration) on your behalf with registrars they work with. if njalla gets a complaint about your domain, in this case from tucows about CSAM on nitter.net they are legally obligated to forward it and follow up. njalla is charging people extra to act as a proxy so they dont have their info exposed. it's run by ex-or-current pirate bay people who seem to want nothing to do with it.

we had a run in with them in regards to tucows in 2021 and njalla assured me what happend with nitter today was not something that would ever happen so I've begun the migration process and suggested the ~8k people following me to do the same if they have any njalla domains

**Comment by Apachez-** [comment] 2024-01-14 13:56
> it's run by ex-or-current pirate bay people who seem to want nothing to do with it.

Does not compute... its runned by someone who want nothing to do with it?

Again, there are 3 parties here in the supply chain which you must choose carefully:

- Proper registrar.
- Proper DNS-server hosting.
- Proper WEB-server hosting.

**Comment by stopmotio** [comment] 2024-01-14 13:58
What is "tucows"?

**Comment by animegrafmays** [comment] 2024-01-14 13:59
> What is "tucows"?

one of the oldest registrars in north america. in this case, njalla is acting as a proxy registering or maintaining registration for domains via tucows ([tucows.com](https://tucowsdomains.com/))

you can see this via `whois nitter.net`

**Comment by jaw-sh** [comment] 2024-01-14 17:03
Have you discerned if this was Tucows or the NIC? Njalla says it was the responsibility of .ORG's NIC, but you're on .NET which is owned by Verisign, while .ORG is managed by the Public Interest Registry.

**Comment by zedeus** [comment] 2024-01-14 19:30
Njalla has responded. Good ending I guess, but they clearly didn't enjoy the negative publicity.
![Screenshot_2024-01-14-19-28-15-43_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/zedeus/nitter/assets/9434921/b93158d3-90ae-4ee8-a375-b606806063d2)

**Comment by Satoshi64** [comment] 2024-01-14 19:50
I think the the "New message" title policy is very reasonable but they should tweak it a bit to inform the user the message requires urgent action.

**Comment by lukefromdc** [comment] 2024-01-14 19:59
Simply adding the words "urgent" or at this level maybe "emergency" should be generic enough to protect privacy while getting the urgency of the situation across. Fighting CSAM and nonconsensual nudity is time-sensitive as this stuff spread so fast.

Important thing here is nothing irreversible was done in the process of attempting to take the safest course, had it been impossible to reach support or the issue been blown off this would have been an entirely different matter.  

Twitter themselves also needs to be on the ball about actually hosting this stuff, but Musk has fired so many staffers this might be impossible.

**Comment by stopmotio** [comment] 2024-01-14 20:33
If your email address has been seized by the government you probably deserve what's coming to you. It's not Njalla's responsibility to keep that data, and even if it was they're arguably making it worse than if they hadn't intervened

**Comment by Satoshi64** [comment] 2024-01-14 20:39
> If your email address has been seized by the government you probably deserve what's coming to you. 
That wasn't a very smart take given what the government does in China, Russia and even Europe nowadays.

**Comment by stopmotio** [comment] 2024-01-14 20:47
> > If your email address has been seized by the government you probably deserve what's coming to you. 
> 
> That wasn't a very smart take given what the government does in China, Russia and even Europe nowadays.

Fair, but IMO those safeguards ought to be optional

**Comment by zedeus** [comment] 2024-01-14 20:56
>Fighting CSAM and nonconsensual nudity is time-sensitive as this stuff spread so fast.

@lukefromdc I would agree, but in this case the link wasn't generated by nitter.net so the image would've still been shown if you found the tweet. Also, getting one of dozens of Nitter instances to block one image url is not preventing any spread at all. It would be like contacting VPN or proxy providers to block links. Thankfully Njalla understood this and took note of their mistake.

**Comment by lukefromdc** [comment] 2024-01-14 21:10
Any chance a Nitter user saw the offending content, passed the link to a well-meaning friend for action, and that person didn't realize the content was actually on Twitter and Nitter is just an alternative frontend?

**Comment by jaw-sh** [comment] 2024-01-14 21:13
CSAM is a tool to shut down small websites. There are numerous small platforms (including privacy proxies like Nitter, imageboards like 4chan, even large websites like Omegle) which have closed down due to an inability to moderate CSAM. Big companies have access to paid-for filtering from Microsoft's PhotoDNA or Cloudflare's CSAM Scanning tool, but if you don't have access to those programs, you're just out of luck. It is a very serious emergent threat.

**Comment by zedeus** [comment] 2024-01-14 21:14
I don't believe so. They specifically took a nitter.it link and changed the domain to nitter.net
I don't think anyone did this to take down Nitter as a whole, but it's noteworthy that the link came from another instance, and it's the first time I've gotten a complaint through my domain provider.

**Comment by stopmotio** [comment] 2024-01-14 21:35
In any case, your provider has stated they have made note not to do it again, therefore we can close this issue now

**Closed** 2024-01-15 00:02 UTC

**Comment by trevyn** [comment] 2024-01-15 09:40
Personally, I would like more confidence that Njalla will let you transfer away any domains that they suspend or don’t want to host.

**Comment by lukefromdc** [comment] 2024-01-15 13:45
I certainly would not want to run something like this with my legal name etc on it, so I agree
with the decision not to use a "proper registrar."

**Comment by Apachez-** [comment] 2024-01-15 17:15
> I don't see any issue with how Njalla dealed with the situation. The only problem I see is unwarranted vitriol against a perfectly reputable domain registrar proxy that has been regarded for many years as one of the best for privacy. My experience with Njalla has been excellent, and their conduct has exceeded expectations. Their attitude toward legal complaints is both hilarious (in a good way) and professional, since they play by the rules but they're not pushovers. Their formal writing and PR skills could use some improvement, though.
> 
> While PorkBun sounds interesting, I've never used it, but the last thing I would do is move to whatever a "proper registrar" means. EDIT: It looks like they require personal information, I'm not really sure why porkbun is being considered here. WHOIS privacy means nothing to me.

The issue is that they want their bad behaviour to be erased from the history...

**Comment by lukefromdc** [comment] 2024-01-15 21:23
Consider the heat they'd get if they ignored a complaint about CSAM from a site actually 
hosting it, leaving it showing for say, a week.

**Comment by Apachez-** [comment] 2024-01-25 10:11
Again, forwarding complains is nothing now.

Problem here is that they are trying to erase history that they misbehaved.

**Comment by lukefromdc** [comment] 2024-01-25 18:12
We need to assume that there is no perfect registrar
