### ISSUE TITLE
[Feature Suggestion] Trending Page

### ISSUE THREAD

**Issue by Mennaruuk** [zedeus/nitter#311] opened 2021-01-16 13:03 UTC
I see that [https://nitter.net/explore](https://nitter.net/explore)  redirects to the About page of Nitter. On Twitter, it redirects to the Trending page. Is there a way to implement the Trending page in a privacy-respecting way on Nitter?

**Comment by zedeus** [comment] 2021-01-16 14:31
There is a way to do that, the problem is just how it should be linked. A drop-down menu in the navbar is long overdue, it should be put there, but a new landing page that does a bit more than just username search should also be made. Before at least one of these, a trending page implementation likely won't happen.

**Comment by zedeus** [comment] 2021-12-31 19:27
Since there's also #382, this issue will track support of https://twitter.com/i/trends, and #382 will track https://twitter.com/explore

**Comment by zedeus** [comment] 2022-01-03 01:17
Closing as duplicate of #61

**Closed by zedeus** 2022-01-03 01:17 UTC
Labels: feature parity
