### ISSUE TITLE
Not all media displayed when combined video / gif / images

### ISSUE THREAD

**Issue by Vardor** [zedeus/nitter#906] opened 2023-06-16 21:47 UTC
When a tweet contains different type of media like static images, gif and videos only static images are displayed. I've noted the same behavior in several nitter instances, particularly in the one i've deployed:
https://nitter.altgr.xyz [2023.05.30-38985af](https://github.com/zedeus/nitter/commit/38985af)

Nitter:
![image](https://github.com/zedeus/nitter/assets/39595481/e330beeb-47e2-475f-b552-fd001e7b40a4)  
Twitter: https://twitter.com/masto_bot/status/1669821327799209984?s=20
![image](https://github.com/zedeus/nitter/assets/39595481/88739ce6-f195-467c-a31f-62133b4d988e)

**Comment by zedeus** [comment] 2023-06-16 23:02
I think mixing media like this is a new feature, so Nitter will need special support for it.

**Comment by zedeus** [comment] 2023-06-17 01:39
Oh, this isn't that new. Duplicate of #697

**Closed by zedeus** 2023-06-17 01:39 UTC
Labels: feature parity
