### ISSUE TITLE
Nitter can't be build with nim 1.4.0

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zedeus/nitter#264] opened 2020-10-18 17:45 UTC
```
  Building nitter/nitter using c backend
/home/nitter/nitter/src/formatters.nim(100, 18) Warning: Deprecated since v1.3.1; utcOffset= is deprecated [Deprecated]
/home/nitter/nitter/src/parserutils.nim(150, 11) template/generic instantiation of `?` from here
/home/nitter/nitter/src/parserutils.nim(18, 9) Error: expression 'j`gensym25' is of type 'JsonNode' and has to be used (or discarded)
       Tip: 58 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: nitter
        ... Execution failed with exit code 1
        ... Command: /usr/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.1.0 --path:'/home/nitter/.nimble/pkgs/jester-#7e8df65' --path:/home/nitter/.nimble/pkgs/httpbeast-0.2.2 --path:'/home/nitter/.nimble/pkgs/asynctools-#pr_fix_compilation' --path:'/home/nitter/.nimble/pkgs/asynctools-#pr_fix_compilation' --path:'/home/nitter/.nimble/pkgs/regex-#2e32fdc' --path:/home/nitter/.nimble/pkgs/unicodedb-0.9.0 --path:/home/nitter/.nimble/pkgs/unicodeplus-0.8.0 --path:/home/nitter/.nimble/pkgs/unicodedb-0.9.0 --path:/home/nitter/.nimble/pkgs/segmentation-0.1.0 --path:/home/nitter/.nimble/pkgs/unicodedb-0.9.0 --path:/home/nitter/.nimble/pkgs/nimcrypto-0.4.11 --path:/home/nitter/.nimble/pkgs/karax-1.1.2 --path:/home/nitter/.nimble/pkgs/sass-0.1.0 --path:'/home/nitter/.nimble/pkgs/markdown-#head' --path:/home/nitter/.nimble/pkgs/packedjson-0.2.1 --path:'/home/nitter/.nimble/pkgs/snappy-#d13e2cc' --path:'/home/nitter/.nimble/pkgs/redpool-#57aeb25' --path:'/home/nitter/.nimble/pkgs/redis-#94bcbf1' --path:'/home/nitter/.nimble/pkgs/redis-#94bcbf1' --path:'/home/nitter/.nimble/pkgs/frosty-#0.0.6' --hints:off -o:/home/nitter/nitter/nitter /home/nitter/nitter/src/nitter.nim
```

It seems to be using deprecated code.

**Comment by iomintz** [comment] 2020-10-23 09:32
Can repro on nim 1.4.0 and I can't seem to downgrade, as earlier versions are not compiling for me. Anyone know where I can find precompiled x86_64 nim builds pre 1.4.0 for Linux?

**Comment by alderocas** [comment] 2020-10-23 14:56
@iomintz, looks like you can still download via the nim-lang.org site:

https://nim-lang.org/download/nim-1.2.8-linux_x64.tar.xz  
https://nim-lang.org/download/nim-1.0.10-linux_x64.tar.xz

**Comment by iomintz** [comment] 2020-10-24 18:07
/var/lib/nitter/app/src/parserutils.nim(150, 11) template/generic instantiation of `?` from here
/var/lib/nitter/app/src/parserutils.nim(18, 9) Error: expression 'j`gensym61580022' is of type 'JsonNode' and has to be discarded

i got the same error using 1.2.8. Anyone know what version to use?

**Comment by zedeus** [comment] 2020-10-24 18:39
1.2.6 should be fine for now. A language feature in Nim was removed in 1.2.8 and 1.4, but it has been [reverted](https://github.com/nim-lang/Nim/pull/15700) so it'll be available in the next minor release.

**Comment by iomintz** [comment] 2020-10-24 20:01
1.2.6 confirmed working

**Comment by zedeus** [comment] 2020-10-27 12:27
1.2.8 has just been released, without removing the feature (the one you tried above was a release candidate).

**Comment by somini** [comment] 2020-11-08 12:48
This should be fixed on nim v1.4.2, which is not released yet. Bummer for those of us in rolling releases.

**Closed** 2020-11-10 14:55 UTC

**Comment by ftpmorph** [comment] 2021-02-23 01:10
Getting this issue with 1.4.2. Anyone else?

**Comment by iomintz** [comment] 2021-02-23 09:35
No, I'm not.

**Comment by ftpmorph** [comment] 2021-02-23 10:14
False alarm it was a problem with my machine I had two different nim binaries on my machine, fixed that and it did build but the layout is completely messed up and the instance is rate limited already even though it's a fresh install... but that's a separate issue.
