### ISSUE TITLE
Nitter RSS doesnt include pinned tweets

### ISSUE THREAD

**Issue by rossneilson** [zedeus/nitter#1046] opened 2023-10-19 15:15 UTC
The RSS version of twitter seems to completely remove nitter pinned tweets. It doesn't include them at the top like they show in normal twitter which is good for RSS but actually completely removes the original tweet which was pinned from the RSS feed also.

**Comment by zedeus** [comment] 2023-10-19 20:39
Duplicate of #1042

**Closed by zedeus** 2023-10-19 20:39 UTC
