### ISSUE TITLE
Quotes tweets in RSS feed show whole tweet instead of links

### ISSUE THREAD

**Issue by nikhilCad** [zedeus/nitter#423] opened 2021-08-14 05:02 UTC
Instead of

Reply text
nitter.net/vebe101/status/1424714712042807300#m

Show

Reply text
>Original text which was quoted

in the RSS feed

**Comment by Ducklett** [comment] 2021-09-19 21:03
I'd also like to see something like this implemented
Nitter rss feeds currently use `<dc:creator>` to identify authors of retweets, so quote tweets could do the same.
I guess retweets of quote tweets would need two `<dc:creator>` tags (first for retweet, second for quote tweet)

**Comment by zedeus** [comment] 2022-01-03 08:13
Duplicate of #132

**Closed by zedeus** 2022-01-03 08:13 UTC
Labels: enhancement, RSS
