### ISSUE TITLE
Nitter search not working

### ISSUE THREAD

**Issue by ParamoreFan** [zedeus/nitter#898] opened 2023-06-06 00:00 UTC
Title says it all

**Comment by pin-grid-array** [comment] 2023-06-06 07:00
Search is working fine for me right now.

Are you using a public instance? If so, which one? If you are self hosting, are you using the most up-to-date Nitter? What search terms and filters are you using? 

I saw that you posted [another thread where you said that videos aren't playing properly](https://github.com/zedeus/nitter/issues/894#issue-1737351092) but you didn't provide any info there either about how you are trying to access them. These questions could apply to that thread too. The more info you provide, the more likely somebody is able to help you find the problem.

**Comment by zedeus** [comment] 2023-06-06 07:41
Closing since search works with the latest version of Nitter, and there's no information to go off of. Feel free to provide more information and reopen.

**Closed by zedeus** 2023-06-06 07:41 UTC

**Comment by Trit34** [comment] 2023-06-06 09:05
> Closing since search works with the latest version of Nitter, and there's no information to go off of. Feel free to provide more information and reopen.

Just FYI: last night (1:00 CEST), search was indeed broken and worked only on the first term looked up (“linux xfce” results were only for “linux”, the “xfce” part was ignored). Tested with a friend’s own instance and nitter .net: both were affected.

If it works again as expected today without any changes, I guess it was another breakage caused by “this guy”, then… Just before, there were some errors “Tweet not found” (while they exist) and no tweets shown on profiles pages for five minutes.
