### ISSUE TITLE
Timeline is only partial

### ISSUE THREAD

**Issue by stemy2** [zedeus/nitter#290] opened 2020-12-03 21:49 UTC
Hello,

I can't see all the tweet from users. For example: with netflix, the most ancient tweet i can see on nitter is dated at nov 16, and i know there are actually more ancient tweets but the button "load more" disappeard.

**Comment by zedeus** [comment] 2020-12-06 00:09
Closing as duplicate of #289

**Closed by zedeus** 2020-12-06 00:09 UTC
