### ISSUE TITLE
429 Too Many Requests, can't load profile feed

### ISSUE THREAD

**Issue by kernel-panicd** [zedeus/nitter#525] opened 2022-01-22 11:00 UTC
The feed of every profile reports "no item found" in the "tweets" tab with a nonempty twitter feed, while other tabs display it correctly.
While the debug flag is set in the settings, the systemd unit reports "429 Too Many Requests" when loading the feed.
On Debian 10 with nginx, compiled with nim 1.4.8 [Linux: amd64]

**Comment by chrislombardo** [comment] 2022-01-22 18:22
nitter.actionsack.com is having this issue.  No new tweets in RSS feeds for since Jan 20.

**Comment by acarasimon96** [comment] 2022-01-22 19:39
We are totally aware of this and currently tracking it in #481, despite that it was closed as of writing. Zedeus pushed a (temporary) fix for this yesterday, so they should work again once you build Nitter against the latest commit. I'm not a maintainer but unfortunately this is a duplicate of #481.

**Comment by zedeus** [comment] 2022-01-22 21:34
This issue was fixed two days ago in https://github.com/zedeus/nitter/commit/cdb4efadfeb5102b501c7ff79261fefc7327edb9, please check if the instance you use is on that commit or newer.

**Closed by zedeus** 2022-01-22 21:34 UTC

**Comment by kernel-panicd** [comment] 2022-01-23 14:05
Thanks for your work!
