### ISSUE TITLE
[QUESTION] Run nitter behind reverse proxy

### ISSUE THREAD

**Issue by esturniolo** [zedeus/nitter#453] opened 2021-10-12 01:00 UTC
Hi guys.

I'm trying to add this service to my server, but I can't.

I'm using this compose (the original one, with some modifications to run in my own infrastructure)

```
version: "3.8"
services:
  redis:
    image: redis:6-alpine
    container_name: ${CONTAINERNAME}_redis
    restart: unless-stopped
    volumes:
      - ${CONTAINERDIR}/config/redis:/var/lib/redis
    networks:
      mynetwork:
        ipv4_address: 172.20.0.36
  nitter:
    image: zedeus/nitter:latest
    container_name: ${CONTAINERNAME}
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ${CONTAINERDIR}/config/nitter.conf:/src/nitter.conf
    networks:
      mynetwork:
        ipv4_address: 172.20.0.37
networks:
  mynetwork:
    external: true
```
The fact is that when I run the container, the logs only loops with start.sh not found...

I'm starting with selfhosting and I can't realize the problem.
Where is my error?

Using this compose I can run my apps with https and avoid to open ports (the port is specified in the nginx config file for nitter)

Thanks in advance.

**Comment by Salastil** [comment] 2021-11-28 01:00
Issue is old but the problem is that you didn't add in the ports for either docker container in your compose. Nginx or whatever you chose to reverse proxy will be interacting from the port you exposed.

**Closed** 2021-12-20 01:06 UTC
