### ISSUE TITLE
Videos not playing on nitter.net

### ISSUE THREAD

**Issue by WOnder93** [zedeus/nitter#1147] opened 2024-01-10 14:09 UTC
They were still working a couple days ago. Any idea what's wrong?

**Comment by ElTioRata** [comment] 2024-01-10 17:08
Some videos that are a few seconds long do play for me but longer videos don't.

**Comment by tonytonyistony** [comment] 2024-01-10 17:18
Experiencing the same issue for the past few days

**Comment by WOnder93** [comment] 2024-01-10 17:27
Actually I found [a (long) video](https://nitter.net/rabbit_hmi/status/1744781083831574824#m) that seems to play fine. OTOH many others like [this one](https://nitter.net/ResoluteSquare/status/1744752186121163058#m) still won't play.

**Comment by rcsavo** [comment] 2024-01-11 01:53
In my case, deactivating the proxy video streaming and a hard refresh (Ctrl + Shift + r) got the videos working again.

**Comment by tonytonyistony** [comment] 2024-01-11 02:16
> In my case, deactivating the proxy video streaming and a hard refresh (Ctrl + Shift + r) got the videos working again.

Confirmed. This worked for me.

**Comment by ElTioRata** [comment] 2024-01-11 03:05
Yep. Seems like issue is with the proxy. Works flawlessly after disabling that option.

**Comment by jackyzy823** [comment] 2024-01-11 07:45
Two bugs here.

1. nitter currently not support proxying `cmaf` container : because 
    `#EXT-X-MEDIA:NAME="Audio",TYPE=AUDIO,GROUP-ID="audio-128000",AUTOSELECT=YES,URI="/ext_tw_video/xxxxx/pu/pl/mp4a/128000/xxxxxx.m3u8?container=cmaf"` is not proxied in [`proxifyVideo`](https://github.com/zedeus/nitter/blob/b62d73dbd373f08af07c7a79efcd790d3bc1a49c/src/formatters.nim#L80-L89).
     
3.  current hls.js version might not work well with this container.  (the latest 1.5.1 works well)

**Comment by zedeus** [comment] 2024-01-12 02:54
Fixed in https://github.com/zedeus/nitter/commit/52db03b73ad5f83f67c83ab197ae3b20a2523d39, live on nitter.net

**Closed by zedeus** 2024-01-12 02:54 UTC
