### ISSUE TITLE
No pictures in the feed

### ISSUE THREAD

**Issue by felixpalazuelos** [zedeus/nitter#910] opened 2023-06-21 22:50 UTC
This is a problem in old safari versions. I can only use iOS 10 in my phone at the moment. I only see a black box instead of the image, but if I press it it opens the image in a new window.

I know iOS 10 is old, but for a web it isn’t even using JS why is it not able to show the picture? Couldn’t you, please, put a fallback to show the image like an html img tag please?

**Comment by zedeus** [comment] 2023-06-21 22:57
Duplicate of #822

**Closed by zedeus** 2023-06-21 22:57 UTC
