### ISSUE TITLE
Nitter Accounts

### ISSUE THREAD

**Issue by Loki-L1130** [zedeus/nitter#469] opened 2021-11-22 05:43 UTC
I think that like Invidious, You can make accounts for users. Usually we all use Nitter to see What's new in the accounts we follow. Most do so by following them in RSS Feeds of Nitter. But RSS Feeds still needs to be refined. 

So, I think accounts like Invidious just to follow them and showing What's New in HomePage  like in Twitter would be great a lot.

To Manage Databases, I think you can use IPFS and automatic account deletion if remains inactive for Certain Period of Time.

I mean just to view those like a feed in a single Homepage like Twitter does. Which will anyway cannot be used to make Tweets.

@zedeus, If you are not interested in this or any major problems are there Please discuss it here and look for solutions and then close this issue if none are available. Instead of just closing this with a comment.

**Comment by zedeus** [comment] 2022-01-03 04:57
Duplicate of #202

**Closed by zedeus** 2022-01-03 04:57 UTC
Labels: enhancement
