### ISSUE TITLE
An error has occured in one of your routes

### ISSUE THREAD

**Issue by Joopjr** [zedeus/nitter#424] opened 2021-08-15 11:01 UTC
When trying to view RSS feeds I get an error. It seems that this error appears randomly on the pages that should show the RSS feed on nitter.net

```
An error has occured in one of your routes.
Detail: redis.nim(122) raiseReplyError
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
redpool.nim(61) getCachedRssIter
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
Expected '$' at the beginning of a status reply got ':'
```

**Comment by PeterDaveHello** [comment] 2021-08-15 13:29
The interesting thing here is that Nitter.net seems to return some random content to the RSS requests, I just received some Japanese feeds I didn't subscribe to.

**Comment by zedeus** [comment] 2021-08-16 08:22
Welp, this is the second major bug that made me shut down nitter.net some months back, I thought it got fixed with the recent changes. I don't know what's wrong or how to reproduce it

**Comment by PeterDaveHello** [comment] 2021-08-16 10:29
@zedeus I still got some strange result from the RSS feeds, about 15 hours ago, maybe you can use a RSS read/aggregator to reproduce it?

**Comment by acarasimon96** [comment] 2021-08-16 20:20
For what it's worth, I'm not encountering the random user RSS bug on my private instance, and my server is running the latest commit build. But I've seen this same bug about half the time on [nitter.pussthecat.org](https://nitter.pussthecat.org/)

**Comment by PeterDaveHello** [comment] 2021-08-17 07:27
@acarasimon96 is nitter.pussthecat.org hosted by you? I wonder if it's the different loading caused the problem(assume that private instance will not have the same but lower load than the public instance)

**Comment by acarasimon96** [comment] 2021-08-17 14:02
No, I don't own or run nitter.pussthecat.org; that is someone else's public instance. Are you seeing the random user RSS bug on a private or public instance?

**Comment by PeterDaveHello** [comment] 2021-08-17 14:55
> No, I don't own or run nitter.pussthecat.org; that is someone else's public instance. Are you seeing the random user RSS bug on a private or public instance?

I only face the problem on nitter.net currently, but I didn't use a wide range of nitter instance. We need some owners of those instances with the issue to dig deeper.

**Comment by PeterDaveHello** [comment] 2021-08-17 15:50
I just set up a instance on the Onion service: http://6wtik35qytedxazoefyol74tb5qnwknxj3plr4czxlywlod5avkxskyd.onion/, and send another pull request to privacy-redirect (https://github.com/SimonBrazell/privacy-redirect/pull/280), hopefully we can observe something when there are some traffic.

**Comment by acarasimon96** [comment] 2021-08-18 19:04
I've encountered the random user RSS bug on nitter.kavin.rocks (another public instance not run by me) with the following link just now: https://nitter.kavin.rocks/loveliveevents/rss
The interesting part is that the site's [about page](https://nitter.kavin.rocks/about) is running the latest commit build (fd384ff).

CC @FireMasterK since I think he's the owner of that instance.

**Comment by FireMasterK** [comment] 2021-08-18 19:41
> Edit: Looks like nitter.kavin.rocks went down probably due to a Nitter update. It's now returning a Cloudflare 502 Bad Gateway error page.

Fixed, thanks for the report @acarasimon96! It was due to my server running out of space, and not a problem in nitter.

**Comment by acarasimon96** [comment] 2021-08-18 19:55
> It was due to my server running out of space

Let's hope that this is the case. Also, I'm opening a new issue to continue the discussion on the random user RSS feed bug because at this point, I believe this issue has been polluted with comments not related to the original intention of this issue.

**Comment by PeterDaveHello** [comment] 2021-08-19 09:58
As @FireMasterK mentioned that the disk out of space issue will cause the problem, I can reproduce the problem with following different error messages:

```
An error has occured in one of your routes.

Detail: supersnappy.nim(90) uncompress
asyncfutures.nim(390) read
asyncfutures.nim(390) read
Invalid buffer, unable to uncompress
```

```
An error has occured in one of your routes.

Detail: redis.nim(122) raiseReplyError
asyncfutures.nim(390) read
asyncfutures.nim(390) read
redpool.nim(66) cacheProfileIdIter
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
Expected ':' at the beginning of a status reply got '$'
```

```
Detail: redis.nim(126) raiseRedisError
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
redpool.nim(66) getProfileIdIter
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
-MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

**Comment by PeterDaveHello** [comment] 2021-08-25 06:03
Not sure if it's related, but the RSS feed from nitter.net seems to have a huge delay, I just received this tweet three hours ago: https://nitter.net/githubstatus/status/1429815478193639425#m

**Comment by stemy2** [comment] 2021-10-04 09:54
Same problem.

```
An error has occured in one of your routes.

Detail: redis.nim(122) raiseReplyError
asyncfutures.nim(390) read
asyncfutures.nim(390) read
redpool.nim(66) cacheProfileIdIter
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
asyncfutures.nim(390) read
Expected ':' at the beginning of a status reply got '6'
```

**Comment by PeterDaveHello** [comment] 2021-11-03 11:20
> I just set up a instance on the Onion service: [http://6wtik35qytedxazoefyol74tb5qnwknxj3plr4czxlywlod5avkxskyd.onion](http://6wtik35qytedxazoefyol74tb5qnwknxj3plr4czxlywlod5avkxskyd.onion/), and send another pull request to privacy-redirect ([SimonBrazell/privacy-redirect#280](https://github.com/SimonBrazell/privacy-redirect/pull/280)), hopefully we can observe something when there are some traffic.

Doesn't seem to be able to replicate the issue here, and it's been a while, I'll turn this instance down.

**Comment by zedeus** [comment] 2021-12-30 01:59
I haven't seen this issue for quite a while, please reopen if it happens again.

**Closed by zedeus** 2021-12-30 01:59 UTC
