### ISSUE TITLE
UI Changes for some parts

### ISSUE THREAD

**Issue by Loki-L1130** [zedeus/nitter#524] opened 2022-01-22 10:54 UTC
I think when viewing a profile or a tweet it could be better to have a wide UI like in libreddit and also when viewing a profile it feels empty on the sides I think it would be better to either make it wide or detach the Account Information and make it follow along the sides.

**Comment by zedeus** [comment] 2022-01-22 21:45
Duplicate of #17, #248, and #255

**Closed by zedeus** 2022-01-22 21:45 UTC
