### ISSUE TITLE
"No items found" on multi-user feed

### ISSUE THREAD

**Issue by ShahramMohammed** [zedeus/nitter#859] opened 2023-04-29 07:17 UTC
Nitter no longer shows anything on the multi-user feed.
If it is unclear what I mean by mult-user feed, this is what: https://nitter.net/example1,example2,example3

Individual accounts work fine.

**Comment by zedeus** [comment] 2023-04-29 09:30
Uses search, so duplicate of #852

**Closed by zedeus** 2023-04-29 09:30 UTC
