### ISSUE TITLE
Complete Gallery View 

### ISSUE THREAD

**Issue by Fmoment1** [zedeus/nitter#648] opened 2022-06-25 06:50 UTC
As of now, if you visit a user's profile (say, an artist's), you can see a 4x4 view of their media posts. How about giving us an option to see ALL the media posts in this view? A gallery comprising of all their works/image posts, I mean.

![Screenshot_20220625-120946-172](https://user-images.githubusercontent.com/28984045/175762188-8909f9b6-6c5d-4313-ba02-e7704eb08d4b.png)

In this case, I can only see 16 tiles/images, I thought it would be nice if I could go through all 1812 of them in this view. There are apps which already do this, so I'm wondering if it would be possible to implement this as an option? Perhaps even allowing us to set the sizes of the tiles/images in this view.

I'd really appreciate it if this were considered, thank you.

**Comment by zedeus** [comment] 2022-06-25 16:07
Duplicate of #199

**Closed by zedeus** 2022-06-25 16:07 UTC

**Comment by zedeus** [comment] 2022-06-26 15:10
"not planned" is just what GitHub picked as the text as opposed to "completed", it is planned
