### ISSUE TITLE
Direct Messages

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#195] opened 2020-06-19 12:16 UTC
I can list many reasons, why Nitter probably wouldn't be great for logging in and so on, but I need to use DMs often enough that email notifications aren't enough. I end up keeping twitter open as a pin. It also drains loads of performance and privacy.

**Comment by FireMasterK** [comment] 2020-06-20 22:48
I think this a duplicate duplicate of #155 because it covers this

**Comment by zedeus** [comment] 2020-06-20 22:57
Yeah, you can add it in a comment there

**Closed by zedeus** 2020-06-20 22:57 UTC
