### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by pluja** [zedeus/nitter#606] opened 2022-04-11 15:53 UTC
It would be very nice to have a REST API available to develop things on top of Nitter. I don't know how hard would it be to implement a basic REST API that allows to get, for example, a user profile and all their tweets as a PoC. Are there any plans to implement such thing?

**Comment by zedeus** [comment] 2022-04-12 13:04
Duplicate of #192

**Closed by zedeus** 2022-04-12 13:04 UTC
