### ISSUE TITLE
Unable to view list of multiple accounts using URL - "No Items Found"

### ISSUE THREAD

**Issue by Deagan** [zedeus/nitter#860] opened 2023-04-29 20:27 UTC
I can normally view a feed of multiple Twitter accounts, using a comma separated list within the URL (see below).

**Example URLs:**
- https://nitter.net/elonmusk,potus,bycloudai

- https://nitter.net/elonmusk,potus,bycloudai/with_replies

![image](https://user-images.githubusercontent.com/19179570/235323280-348277c1-38b7-48d0-af95-dd29a0596296.jpeg)

This has been returning "No Items Found" for a while now, regardless of selected instance.

I know I can follow a custom Twitter List, but I prefer using this comma listed method for following users.

Was there a change to Twitter/Nitter preventing this view?

Was there a similar view that can be achieved without a Twitter List?

**Comment by zedeus** [comment] 2023-04-29 22:03
Duplicate of #855 and #852

**Closed by zedeus** 2023-04-29 22:03 UTC
