### ISSUE TITLE
Hide Unsafe Media by Default

### ISSUE THREAD

**Issue by Sosasees** [zedeus/nitter#417] opened 2021-08-03 20:08 UTC
I noticed that Nitter doesn't hide Unsafe Media.
That means that if you accidentally stumble upon it, you're helplessly exlosed to it, which is especially bad for children.

Before viewing unsafe media, Nitter should first replace it with a warning, just like official Twitter does:
![](https://user-images.githubusercontent.com/66305550/128077712-59f26963-1780-4200-9e4a-bcfec2fb3bae.png)

---

Of course, this behaviour should be changeable in a settings option (named something like "Unsafe Media"):
- Hide behind Warning (Default)
- Show All (Not Recommended)
- Hide Completely

But before programming that, we should first have the Warning feature in the first place:
The Warning feature being missing
is like having "Show All" as the only "Unsafe Media" option,
so the Warning feature should be added very soon.

**Comment by zedeus** [comment] 2022-01-02 10:49
Closing as duplicate of #225

**Closed by zedeus** 2022-01-02 10:49 UTC
Labels: feature parity
