### ISSUE TITLE
Add legal/imprint/about

### ISSUE THREAD

**Issue by utzer** [zedeus/nitter#460] opened 2021-11-11 19:32 UTC
In most of the EU there is some link to contact details and imprint needed. 

Please a config option for this to be able to have a link somewhere (no matter where) visible with a linked text of choice linking to some URL or even better displaying the content of some html file given in the config. 

Without this it is a bit problematic to run a nitter instance within the EU.

**Comment by zedeus** [comment] 2021-11-14 00:28
The about.md page can be modified, is that enough?

**Comment by zedeus** [comment] 2021-12-30 22:11
Closing as duplicate of #15

**Closed by zedeus** 2021-12-30 22:11 UTC

**Comment by utzer** [comment] 2022-05-10 08:55
Sorry, I just remembered this question and looked for the issue. 

So basically I need to wget [about.md](https://github.com/zedeus/nitter/blob/master/public/md/about.md) from [here](https://raw.githubusercontent.com/zedeus/nitter/master/public/md/about.md) and then edit it, then I need to tell docker to replace that file with an external file (external as not in the docker image). Right?

**Comment by zedeus** [comment] 2022-05-10 09:57
Yes, though that won't get you all the way there. about.md gets compiled to a html file, this is the `nimble md` command run inside the Dockerfile. You could technically modify the html file directly if that's easier for you, otherwise modifying the file and rebuilding the docker image might be best.

**Comment by utzer** [comment] 2022-05-10 21:17
ok., I need to get into building the docker myself, I usually just got the one from docker. Sorry not really much into docker yet.
