### ISSUE TITLE
Video playback broken - "index out of bounds, the container is empty"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zedeus/nitter#512] opened 2022-01-12 17:36 UTC
Since a recent-ish commit, video playback has been broken with clients receiving a 502:

```
An error has occured in one of your routes.

Detail: fatal.nim(49) sysFatal
asyncfutures.nim(390) read
asyncfutures.nim(390) read
index out of bounds, the container is empty
```

(by the way, there's a typo in this stacktrace, it's "occurred" not "occured")

I started to notice this stacktrace in the nitter logs, but I didn't know what caused it, and nothing seemed broken so I ignored it, but it was reported to me today by @B0pol that video playback was broken: this is what is causing it.

---

Running latest master

Nim 1.4.8 (I suspect this is why you don't encounter the issue since you seem to only test on latest)

Nimble 0.013.1

Both video proxy enabled, or disabled are affected.

Example URL: https://nitter.pussthecat.org/elonmusk/status/1480326831031173124

**Comment by zedeus** [comment] 2022-01-12 17:47
I can't reproduce with 1.4.8 or 1.6.2 (latest stable version which I always use). What version of PCRE is installed in the environment where Nitter runs?

**Comment by TheFrenchGhosty** [comment] 2022-01-12 17:50
@zedeus Looks like I don't have it installed, is that the issue?

Is that a new dependency?

**Comment by zedeus** [comment] 2022-01-12 17:53
It has always been a dependency, it's just used more places now. Can I get you to compile a debug build (without -d:release/-d:danger) and post the full stacktrace here?

**Comment by TheFrenchGhosty** [comment] 2022-01-12 17:59
>It has always been a dependency, it's just used more places now.

... I haven't had any issue without it before... weird


Here's the full stacktrace:

```
/home/nitter/nitter/src/nitter.nim(60) nitter
/home/nitter/.nimble/pkgs/jester-0.5.0/jester.nim(511) serve
/usr/lib/nim/pure/asyncdispatch.nim(1930) runForever
/usr/lib/nim/pure/asyncdispatch.nim(1627) poll
/usr/lib/nim/pure/asyncdispatch.nim(1368) runOnce
/usr/lib/nim/pure/asyncdispatch.nim(208) processPendingCallbacks
/usr/lib/nim/pure/asyncmacro.nim(29) matchNimAsyncContinue
/home/nitter/nitter/src/routes/media.nim(127) matchIter
/home/nitter/nitter/src/formatters.nim(90) proxifyVideo
/usr/lib/nim/system/fatal.nim(49) sysFatal
[[reraised from:
/home/nitter/nitter/src/nitter.nim(60) nitter
/home/nitter/.nimble/pkgs/jester-0.5.0/jester.nim(511) serve
/usr/lib/nim/pure/asyncdispatch.nim(1930) runForever
/usr/lib/nim/pure/asyncdispatch.nim(1627) poll
/usr/lib/nim/pure/asyncdispatch.nim(1368) runOnce
/usr/lib/nim/pure/asyncdispatch.nim(208) processPendingCallbacks
/usr/lib/nim/pure/asyncmacro.nim(29) dispatchNimAsyncContinue
/usr/lib/nim/pure/asyncmacro.nim(145) dispatchIter
/usr/lib/nim/pure/asyncfutures.nim(390) read
]]
[[reraised from:
/home/nitter/nitter/src/nitter.nim(60) nitter
/home/nitter/.nimble/pkgs/jester-0.5.0/jester.nim(511) serve
/usr/lib/nim/pure/asyncdispatch.nim(1930) runForever
/usr/lib/nim/pure/asyncdispatch.nim(1627) poll
/usr/lib/nim/pure/asyncdispatch.nim(1368) runOnce
/usr/lib/nim/pure/asyncdispatch.nim(208) processPendingCallbacks
/usr/lib/nim/pure/asyncmacro.nim(29) handleRequestSlowNimAsyncContinue
/usr/lib/nim/pure/asyncmacro.nim(145) handleRequestSlowIter
/usr/lib/nim/pure/asyncfutures.nim(390) read
]]
index out of bounds, the container is empty
Async traceback:
/home/nitter/nitter/src/nitter.nim(60) nitter
/home/nitter/.nimble/pkgs/jester-0.5.0/jester.nim(511) serve
/usr/lib/nim/pure/asyncdispatch.nim(1930) runForever
/usr/lib/nim/pure/asyncdispatch.nim(1627) poll
/usr/lib/nim/pure/asyncdispatch.nim(1368) runOnce
/usr/lib/nim/pure/asyncdispatch.nim(208) processPendingCallbacks
/usr/lib/nim/pure/asyncmacro.nim(29) matchNimAsyncContinue
/home/nitter/nitter/src/routes/media.nim(127) matchIter
/home/nitter/nitter/src/formatters.nim(90) proxifyVideo
/usr/lib/nim/system/fatal.nim(49) sysFatal
#[
/home/nitter/nitter/src/nitter.nim(60) nitter
/home/nitter/.nimble/pkgs/jester-0.5.0/jester.nim(511) serve
/usr/lib/nim/pure/asyncdispatch.nim(1930) runForever
/usr/lib/nim/pure/asyncdispatch.nim(1627) poll
/usr/lib/nim/pure/asyncdispatch.nim(1368) runOnce
/usr/lib/nim/pure/asyncdispatch.nim(208) processPendingCallbacks
/usr/lib/nim/pure/asyncmacro.nim(29) dispatchNimAsyncContinue
/usr/lib/nim/pure/asyncmacro.nim(145) dispatchIter
/usr/lib/nim/pure/asyncfutures.nim(390) read
]#
Exception message: index out of bounds, the container is empty
```

**Comment by TheFrenchGhosty** [comment] 2022-01-12 18:00
Actually, never-mind, I do have `pcre` installed, version 8.45

For whatever reason my grep didn't see it.

**Comment by zedeus** [comment] 2022-01-12 18:03
Alright, same here, so that's not an issue. `proxifyVideo` was rewritten to not use regex as well, so it's definitely not that. I can't reproduce locally with the latest commit on 1.4.8 or 1.6.2 so I'm not sure what's going on yet. Can you try deleting `~/.nimble/pkgs` then build it again? Maybe it's using outdated packages from when I using the `#head` tag for a few packages (Nimble treats that as "latest" even when they're ancient).

**Comment by TheFrenchGhosty** [comment] 2022-01-12 18:06
Cleared the whole `~/.nimble` directory, rebuilt, restarted, issue is still here.

**Comment by zedeus** [comment] 2022-01-12 18:08
Can you add an echo like this to `proxifyVideo` so we can see what it's processing? Maybe there's a deeper problem
![image](https://user-images.githubusercontent.com/9434921/149197306-9557c12a-af22-4e51-b62c-b2f22e579fcf.png)

**Comment by zedeus** [comment] 2022-01-12 18:09
It's in nitter/src/formatters.nim

**Comment by TheFrenchGhosty** [comment] 2022-01-12 18:11
@zedeus Here's a random one:

```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=632000,BANDWIDTH=632000,RESOLUTION=320x426,CODECS="mp4a.40.2,avc1.4d001e"
/ext_tw_video/1469253617718681602/pu/pl/320x426/Q-bInLMRoMirYrEM.m3u8?container=fmp4
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=950000,BANDWIDTH=950000,RESOLUTION=480x640,CODECS="mp4a.40.2,avc1.4d001f"
/ext_tw_video/1469253617718681602/pu/pl/480x640/KgrDERdJnSNauQlJ.m3u8?container=fmp4
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2176000,BANDWIDTH=2176000,RESOLUTION=720x960,CODECS="mp4a.40.2,avc1.640020"
/ext_tw_video/1469253617718681602/pu/pl/720x960/r8n6IcsLQWzDk-9g.m3u8?container=fmp4
```

**Comment by zedeus** [comment] 2022-01-12 18:11
Does this one cause a crash? Just to make sure I follow

**Comment by TheFrenchGhosty** [comment] 2022-01-12 18:11
It doesn't cause a crash, it just errors out, and break video playback.

**Comment by zedeus** [comment] 2022-01-12 18:12
Alright, thank you. I'll keep you updated

**Comment by TheFrenchGhosty** [comment] 2022-01-12 18:12
@zedeus Thank you, hope you can find the issue.

**Comment by zedeus** [comment] 2022-01-12 18:20
I could reproduce it with the manifest you sent, not sure why we get different ones. Should be fixed now.

**Closed** 2022-01-12 18:20 UTC
Labels: bug

**Comment by TheFrenchGhosty** [comment] 2022-01-12 19:23
@zedeus I can confirm that it's working, thanks!
