### ISSUE TITLE
Hide replies through get method

### ISSUE THREAD

**Issue by user451421541757324** [zedeus/nitter#677] opened 2022-08-04 11:44 UTC
I'm aware that replies can be hided through settings: is it possible to add another way to do that by a get method?

For example:
https://nitter.net/ScuderiaFerrari/status/1554857012407795712?replies=0

It's useful if you want to link a tweet to non-nitter users.

**Comment by zedeus** [comment] 2022-08-04 11:46
>if you want to link a tweet to non-nitter users

Why would hiding replies have any relevance here? You could use the embed, e.g. https://nitter.net/ScuderiaFerrari/status/1554857012407795712/embed
Otherwise, this is a duplicate of #186

**Closed by zedeus** 2022-08-04 11:46 UTC
