### ISSUE TITLE
Accounts: Private/Personal RSS Feed

### ISSUE THREAD

**Issue by trymeouteh** [zedeus/nitter#204] opened 2020-07-03 19:00 UTC
Once accounts are added, please allow us to have a personal and private RSS feed for our account to allow us to read out nitter twitter feed in our RSS reader.

**Comment by zedeus** [comment] 2022-01-03 04:57
Duplicate of #202 since turning your feed into RSS is within the scope of an account system

**Closed by zedeus** 2022-01-03 04:57 UTC
