### ISSUE TITLE
Tweets tab on user profiles doesn't show recent tweets

### ISSUE THREAD

**Issue by fuzxi** [zedeus/nitter#962] opened 2023-07-21 04:29 UTC
All the profiles I checked are missing several years of, if not all, of their tweets. Does not appear to be instance-specific, I see this on both nitter.net and my personal instance. The Tweets & Replies tab works normally. 
![2023-07-20-21-23-38](https://github.com/zedeus/nitter/assets/33790641/d9ced633-e442-4261-bafa-096a63740f7a)
![2023-07-20-21-23-46](https://github.com/zedeus/nitter/assets/33790641/e247c934-6de0-46b5-8165-95f67992d20b)
![2023-07-20-21-24-28](https://github.com/zedeus/nitter/assets/33790641/f2aecf92-89b2-4415-8b10-323fac61a3cb)
![2023-07-20-21-24-33](https://github.com/zedeus/nitter/assets/33790641/609ed7ab-ca78-420c-a197-a6a59793449c)

**Comment by ImTheDeveloper** [comment] 2023-07-21 05:42
Data missing in the standard user tweets end point https://github.com/zedeus/nitter/issues/961#issuecomment-1645011111

**Comment by shuttershutter** [comment] 2023-07-21 06:06
One temporary workaround for me is to click on the "search" tab (next to the media tab) in the user profile, and it will show the most recent tweets.

**Comment by Trit34** [comment] 2023-07-21 07:57
RSS feeds are not working either (`User "XXX" not found`). Surely related to #953.

**Comment by zoubidabida** [comment] 2023-07-21 10:32
Same here on my personal instance. This for example returns very old and random tweets. It’s usually updated daily : [Rer_a](https://nitter.net/rer_a)

**Comment by SigmaTheDJ** [comment] 2023-07-21 14:53
Is it because of this?.....

[Deprecation of the /1.1/guest/activate/ endpoint in the Twitter API ](https://twittercommunity.com/t/deprecation-of-the-1-1-guest-activate-endpoint-in-the-twitter-api/200591)

**Comment by zedeus** [comment] 2023-07-21 17:06
Fixed by https://github.com/zedeus/nitter/commit/cc5841df308506356d329662d0f0c2ec4713a35c

**Closed by zedeus** 2023-07-21 17:06 UTC

**Comment by zoubidabida** [comment] 2023-07-21 17:54
> Fixed by [cc5841d](https://github.com/zedeus/nitter/commit/cc5841df308506356d329662d0f0c2ec4713a35c)

I just applied the patch. It works on some users but not for others. 
Like this one : ligne10_ratp which still has outdated tweets

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2023-07-21 18:03
If u go to https://nitter.net/433 u see no tweets but if u refresh a few times u do see them. Refresh again and u dont see them. Is this caused by the fix?

**Comment by zedeus** [comment] 2023-07-21 18:36
@efb4f5ff-1298-471a-8973-3d47447115dc yes, under high load it will unfortunately get temporarily rate limited for a few seconds at a time. It's the only good option for now.

**Comment by edel79** [comment] 2023-07-21 19:37
And this rate limit is per-instance or cumulative for all of them ?
I mean, is it the same if there are 100 requests from 1 instance, or 10 requests for 10 instance, in the same time ? Or not ?

**Comment by zedeus** [comment] 2023-07-21 21:38
Per instance

**Comment by zoubidabida** [comment] 2023-07-22 11:47
> Fixed by [cc5841d](https://github.com/zedeus/nitter/commit/cc5841df308506356d329662d0f0c2ec4713a35c)

Hi !
Since last patch, threads aren’t working any more. 
I’m not getting any threading info. 
(I’m using the main url and not the threads and reply. It used to work fine before that)

**Comment by zedeus** [comment] 2023-07-25 17:42
Correct

**Comment by Trit34** [comment] 2023-07-28 08:03
Today, on the instance I use (ntr.nah.re), “Tweets” tab and RSS feeds work fine again. Until the next break…
