### ISSUE TITLE
Images aren't showing up; only birdsote.xanny.family worked

### ISSUE THREAD

**Issue by WineAunt** [zedeus/nitter#941] opened 2023-07-14 07:01 UTC
Because I'm a dirt poor wine aunt and on 32bit browser, I cannot view the newer webp extension. I noticed that AnyCast https://birdsite.xanny.family/ using cloudfare was the only instance I was able to see all images and videos on users feed, and it worked great. Now every instance, including nitter.net does not load images unless I right-click on page, find image urls, cut out webp extension, and use the .jpg within the url. Then it shows up, but only when I paste in search bar.

Is there any instance that doesn't use webp? I'm sad, and I'm poor! I get that it's probably an issue on my side, but there's got to be one instance like bird.xanny.

**Comment by zedeus** [comment] 2023-07-14 10:01
Duplicate of #webp

**Closed by zedeus** 2023-07-14 10:01 UTC
