### ISSUE TITLE
Twitter count not available in tweet-stats

### ISSUE THREAD

**Issue by katesanalyst** [zedeus/nitter#838] opened 2023-04-21 03:39 UTC
the recent implementation in twitter ; Total no.of views added along with reply, retweet and likes. Whereas nitter does not included so for in tweet-stats section. It would be good to add the same for analytical purposes to calculate engagement rate views.

**Comment by zedeus** [comment] 2023-06-17 02:06
Duplicate of #753

**Closed by zedeus** 2023-06-17 02:06 UTC
Labels: feature parity
