### ISSUE TITLE
"This card type is not supported."

### ISSUE THREAD

**Issue by Emporea** [zedeus/nitter#511] opened 2022-01-12 02:23 UTC
Whats the reason some pictures cant be loaded on via nitter?

An example might be https://nitter.net/Faktillon

**Comment by zedeus** [comment] 2022-01-12 12:13
"Cards" are very complicated link previews and poll embeds that can be a large variety of things. Official documentation is basically nonexistent, but this issue is actually a duplicate of #345 since all the cards on that page are of the type "unified_card"

**Closed by zedeus** 2022-01-12 12:13 UTC
