### ISSUE TITLE
Feature Request: Followers/Following Endpoint

### ISSUE THREAD

**Issue by yitopeligo** [zedeus/nitter#967] opened 2023-07-26 12:57 UTC
I must appreciate this great work of yours!

Currently as seem to be, there isn't any chance to view followers/following persons of an account.

Would be really useful if we access them too.

Thanks.

**Comment by zedeus** [comment] 2023-07-26 13:58
Duplicate of #823 #187

**Closed by zedeus** 2023-07-26 13:58 UTC
