### ISSUE TITLE
How do google and bing still index?

### ISSUE THREAD

**Issue by asdf8dfafjk** [zedeus/nitter#920] opened 2023-07-01 04:56 UTC
This is in the "series" of twitter shutting down unregistered reads but separate enough topic that probably warrants a new issue.

Things that still work without logging in:

1) Indexing by bing and google

2) Embedding

3) Official android app?

No way to know how long the "temporary measure" will last would be nice if there was a work around rather than waiting and being on the mercy of twitter's administration.

**Comment by not-siblers** [comment] 2023-07-01 12:16
Search engine crawlers will use a special user-agent that identifies them as a the crawler they are, so twitter is likely checking for that. On top of that you can verify that you're being crawled by the google crawler rather than someone pretending to be google, see here; https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot

**Comment by trafotin** [comment] 2023-07-01 16:11
Twitter could check for a reverse DNS mask and can confirm this doesn't work. The embedded tweets work too, the question is for how long.
![Twitter with Google Bot user agent](https://github.com/zedeus/nitter/assets/108948841/c5fc32d4-5e1b-4b34-8bd8-fad8a4cff4a4)

**Comment by zedeus** [comment] 2023-07-01 20:05
Duplicate of #919

**Closed by zedeus** 2023-07-01 20:05 UTC
