### ISSUE TITLE
Instance has been rate limited

### ISSUE THREAD

**Issue by stemy2** [zedeus/nitter#305] opened 2021-01-09 11:46 UTC
Hello,

According the readme, there is no rate limits, but since not long ago, i have often the message 

```
Instance has been rate limited.
Use another instance or try again later.
```

I'd like to know why there is actually rate limits even if the readme says there isn't. Did twitter changed something ?

**Comment by girst** [comment] 2021-01-09 18:13
i was wondering the same. it looks like, according to this commit (https://github.com/zedeus/nitter/commit/4e1d21348844d023eada9c8161021f322fedb432), that the rate-limiting is coming from twitter's side, not nitter's.

the error message is a bit ambiguous; maybe @zedeus can add "... by twitter" to it?

**Comment by Mennaruuk** [comment] 2021-01-11 17:43
I've been noticing this error primarily on Nitter.net. It seems like other instances aren't facing the same issue. I'm currently using [FDNitter ](https://nitter.fdn.fr)and it hasn't been rate limited.

**Comment by stemy2** [comment] 2021-01-11 18:03
Nittet.net is not the only instance affected. Maybe an automated redirect to another instance wgen limit is reached could be a good idea.

**Comment by zedeus** [comment] 2021-01-12 14:08
Automatically redirecting will just make DDOSing all instances at the same time easier. I'll work on ways to bypass the rate limits instead.

**Comment by FireMasterK** [comment] 2021-01-12 19:33
Can we add a robots.txt file to further block crawlers?

**Comment by FireMasterK** [comment] 2021-01-12 19:46
I'm not sure if this helps:

My instance used to say rate limited when loading pages, but after reloading the page once it loaded fine

When I restarted my instance, the problem went away entirely.

So, this raises the question - are these ratelimits per token? Can't we just discard rate-limited tokens and fetch new ones?

**Comment by Mennaruuk** [comment] 2021-01-12 21:57
I remember zedeus mentioning last year that it was "[500 tokens per 30 minutes](https://github.com/zedeus/nitter/issues/200#issuecomment-648813934)", I don't know if that still holds true today with the changes to Twitter API v2.

**Comment by zedeus** [comment] 2021-01-13 01:34
From a local test, it seems they actually increased it to 1000 tokens per 30 minutes, which is nice, but apparently not enough for Nitter. I don't understand that though considering that would result in a theoretical max of at least 1 million requests per 15 minutes (I won't get into the math, but it has to do with the rate limit windows and token expiration time). I'm fairly certain my half-assed token pool is the problem, I think it throws away tokens that hit the 15-minute window rate limit instead of saving them for later, but I could be wrong. Some simple logging showed only 19 tokens are in the pool when it hits the rate limit, which makes no sense considering the max of 1000 per 30 minutes.

There's an old API v1.1 timeline endpoint with a rate limit of 1 billion requests per 15 minutes, which is ridiculous. I did a test a while back fetching 100k timelines in a row, and I didn't get limited. This hasn't been used so far due to a different data structure that's far less memory efficient, but it's a possible solution.

So for now the plan is to develop a new token pool, borrowing some ideas from #191, which should solve the problem entirely for a very long time.

**Comment by zedeus** [comment] 2021-01-13 13:44
I've implemented and deployed the ideas from #191, lowering the required amount of tokens needed at any one time by a lot. I did a local test by running 40 while loops fetching a profile timeline with no sleep in between, resulting in ~3 requests per second times 40, for roughly two hours. No rate limits were hit, and the pool maxed out at 360 tokens, which is well below the 1000 limit (or, accounting for the expiration time, 4000 token limit). In fact, with 4000 tokens, this means we have a theoretical max of ~3 million requests per hour, or ~800 per second.

If rate limits are somehow still hit, please let me know.

**Comment by zedeus** [comment] 2021-01-13 22:37
PSA to people hosting public Nitter instances, make sure you block AWS IPs. Nitter has been getting hit massive scraping once a day from 16:40 to 18:15 by 837 AWS IPs, scraping a list of 520k profiles alphabetically. Previously this wasn't an issue, but we recently switched to using Hetzner's load balancer with a few servers, which breaks iptables.

**Comment by Mennaruuk** [comment] 2021-01-15 16:09
To be honest, I’m still being rate-limited every three clicks or so.

**Comment by zedeus** [comment] 2021-01-16 07:47
@Mennaruuk it's due to some faulty logic in the token pool, but I'm not sure what yet. I think Twitter made some changes besides the 500 -> 1000 tokens per 30 min change, maybe expiry time as well, I'll need to do some testing to find out. Restarting Nitter fixes it right away.

**Comment by nklmilojevic** [comment] 2021-01-19 14:27
I host https://nitter.cc and had this problem. My instance was behind Cloudflare and as soon as I removed CF proxy it started working. Leaving this here as it can help others.

**Comment by nklmilojevic** [comment] 2021-01-19 14:28
I host nitter.cc, my instance doesn't work even after restarting it:

```
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
rate limited with 0 tokens, average remaining: 0
fetching token failed: 429 Too Many Requests
rate limited with 0 tokens, average remaining: 0
fetching token failed: 429 Too Many Requests
rate limited with 0 tokens, average remaining: 0
fetching token failed: 429 Too Many Requests
rate limited with 0 tokens, average remaining: 0
fetching token failed: 429 Too Many Requests
```

**Comment by nklmilojevic** [comment] 2021-01-19 14:49
Yup, this is it, I have built my own image from master and now everything works. I suppose that is why others are having the problem - they are pulling from outdated version on dockerhub.

**Comment by nklmilojevic** [comment] 2021-01-19 21:32
For temp fix, you can use my image:

`ghcr.io/nklmilojevic/nitter:0.0.1`

It is from my fork that is available publicly I just modified it to use Github Actions: 

https://github.com/nklmilojevic/nitter

I will delete it as soon as official build is working. If you need help moving nitter to GHA and Github Container Registry, I'll be glad to help.

**Comment by stemy2** [comment] 2021-01-25 09:38
It's getting worse. I can't use nitter without viewing the error message. I must change the instance 5 time per click because of this.

**Comment by Ottaviocr** [comment] 2021-01-25 09:43
I don't want to be overly pessimistic, but I think that Twitter has "de facto" killed Nitter, like they did for other 3rd party rss scrapers that I have used in the recent past.

**Comment by zedeus** [comment] 2021-01-25 09:54
I'm fairly certain it's just due to faulty logic in the token pool.

**Comment by zedeus** [comment] 2021-01-25 10:10
The two latest commits should fix this. I kind of know what the error was, but I don't understand it, so I won't try to explain it.

**Comment by zedeus** [comment] 2021-01-26 01:05
The last problem left is the error I mentioned above, I simply added a workaround. After running for a bit, Nitter starts spitting out a bunch of these errors `Received length doesn't match expected length. Wanted 58114 got 32362` from API requests. I think this is caused by the http pool reusing broken clients, or something like that. I'll look into it this week, it seems like it's the last "rate limit" issue left (it's not actually a rate limit by any means, the API request just fails, returning a rate limit error to the user).

**Comment by melissachang** [comment] 2021-02-03 04:01
I used to see "Instance has been rate limited" sporadically. Starting yesterday, it's 100% of the time, eg https://nitter.net/POTUS/rss

Is this bug to make nitter.net work? I'm wondering if I should wait for nitter.net to work, or switch to a different instance.

**Comment by zedeus** [comment] 2021-02-03 19:42
nitter.net is not really rate limited, I made it display it because I had trouble fixing some issues, and it helps distributing users to other instances. I would encourage you to not use nitter.net as it gets a ton of traffic already. It'll be back soon

**Comment by Perflyst** [comment] 2021-02-04 11:21
real rate limiting still happens on nitter.snopyta.org

**Comment by stemy2** [comment] 2021-02-09 11:02
Until you find an efficient solution, maybe you could do the same thing as invidious when the main instance had been closed: a page listing some working instance, and where you could replace the url https://instance1.tld/account by https://instance2.tld/account in one click. I think it would be more ergonomic than the actual method.

**Comment by m0n5t3r** [comment] 2021-02-14 20:43
I wrote https://gist.github.com/m0n5t3r/b7c13265152bd8c997f2d22afb4932e7 to redirect to a random healthy invidious instance, it works most of the time; is there any API returning the instance list at https://github.com/zedeus/nitter/wiki/Instances?

**Comment by girst** [comment] 2021-02-14 20:53
curl -s https://raw.githubusercontent.com/wiki/zedeus/nitter/Instances.md | grep '^\*' | grep -o '\](.*)' | tr -d ']()'

**Comment by Ottaviocr** [comment] 2021-04-17 17:32
After a few weeks of working fine, now I'm having rate limitation warnings a https://nitter.himiko.cloud/.

**Comment by jtagcat** [comment] 2021-04-18 19:39
Since yesterday, my instance has been blocked 100% of the time.

**Comment by kayg04** [comment] 2021-04-19 04:35
@jtagcat, same, 3+ days now.

**Comment by jtagcat** [comment] 2021-04-19 08:53
I initiated an another instance on a fresh residential IP, the first page I loaded indicated it's being rate limited.

**Comment by Ottaviocr** [comment] 2021-05-12 11:40
Rate limitation has resurfaced gain for https://nitter.40two.app

**Comment by rderensy** [comment] 2021-05-16 22:52
Happy to see I'm not the only one with the problem! What's annoying is that it's a personal instance and I am the only one using it. Also I block every bot/empty user agents so there might be a few random hits from other machines than mine here and there but it should still be extremely low.

Is there a way to solve this? Increasing the number of token in the conf file? Would deleting the Nitter folder and re-cloning work? Or is there a tmp folder or redis server to clean or something?

**Comment by jtagcat** [comment] 2021-05-17 02:19
I've experienced no problems, you might want to try https://n.c7.ee/robots.txt (ye, it's a bit overboard :^) )

**Comment by rderensy** [comment] 2021-05-17 08:23
I am using the same robots.txt as the one provided in https://github.com/zedeus/nitter/wiki/Nginx, so all user-agents are disallowed:
```
User-agent: *
Disallow: /
```

**Comment by utzer** [comment] 2021-06-01 20:50
Anyone know how to server the robots.txt from docker setup with some nginx proxy in front?

**Comment by Ottaviocr** [comment] 2021-06-04 07:38
I have been receiving "Instance has been rate limited." on
https://nitter.40two.app for a few days now.

**Comment by rderensy** [comment] 2021-06-04 07:51
I've been having this message for 18 days now but yesterday, when I tried to load a tweet, I first got the error but refreshing the page fixed it. And refreshing worked several times after that so it might be worth a try if you have the problem.

**Comment by Dr-Dd** [comment] 2021-06-10 20:41
I'm also using a personal instance on my own server, i get rate limited from time to time but just refreshing fixes the problem. I'll quickly post a log, as it seems related to what @zedeus was referring to (as posted by others).

```
Jun 10 22:33:24 archd nitter[100972]: error: Received length doesn't match expected length. Wanted 185716 got 81476, token: (tok: "1403083813367037954", remaining: 186, reset: 2021-06-10T22:32:07+02:00, init: 2021-06-10T22:17:03+02:00, lastUse: 2021-06-10T22:17:08+02:00), url: https://api.twitter.com/2/timeline/profile/807095.json?include_profile_interstitial_type=0&include_blocking=0&include_blocked_by=0&include_followed_by=0&include_want_retweets=0&include_mute_edge=0&include_can_dm=0&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=false&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=false&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&ext=mediaStats&include_quote_count=true&userId=807095&include_tweet_replies=false&ext=mediaStats&count=20
Jun 10 22:33:24 archd nitter[100972]: rate limited with 10 tokens, averag
e remaining: 185
Jun 10 22:33:26 archd nitter[100972]: error: Received length doesn't match expected length. Wanted 185716 got 81476, token: (tok: "1403083813367037954", remaining: 185, reset: 2021-06-10T22:32:07+02:00, init: 2021-06-10T22:17:03+02:00, lastUse: 2021-06-10T22:17:08+02:00), url: https://api.twitter.com/2/timeline/profile/807095.json?include_profile_interstitial_type=0&include_blocking=0&include_blocked_by=0&include_followed_by=0&include_want_retweets=0&include_mute_edge=0&include_can_dm=0&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=false&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=false&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&ext=mediaStats&include_quote_count=true&userId=807095&include_tweet_replies=false&ext=mediaStats&count=20
Jun 10 22:33:26 archd nitter[100972]: rate limited with 10 tokens, average remaining: 184
```

**Comment by zedeus** [comment] 2021-06-11 22:55
@Dr-Dd for small personal instances, you can get away with setting `tokenCount` in nitter.conf to 1, should prevent most of those errors.

I'm sorry for having left the project in an increasingly broken state, I have very little time or energy to work on Nitter at the moment. The major bugs that were left are weird and hard to troubleshoot, it drained my energy.

**Comment by girst** [comment] 2021-06-12 08:02
On Fri, Jun 11, 2021 at 03:56:03PM -0700, Zed wrote:
>I'm sorry for having left the project in an increasingly broken state, 
>I have very little time or energy to work on Nitter at the moment. The 
>major bugs that were left are weird and hard to troubleshoot, it 
>drained my energy.

when a hobby project stops making fun, take a break. you don't owe 
anyone anything. <3

**Comment by Dr-Dd** [comment] 2021-06-12 10:19
> I'm sorry for having left the project in an increasingly broken state, I have very little time or energy to work on Nitter at the moment. The major bugs that were left are weird and hard to troubleshoot, it drained my energy.

You don't owe anyone anything. The fact you provided something so useful that tons of people have been searching for years and for free is more than enough anyone could ever ask for.

Aside from this, maybe it's time to find other mantainers.

**Comment by utzer** [comment] 2021-06-12 11:21
Yes, write a few line that you look for co-maintainers everyone can spread that and maybe some people like to help. Also put that text in /about.

**Comment by Mennaruuk** [comment] 2021-06-13 18:14
Yes, please take care of yourself, that's the most important person in your life.

**Comment by zedeus** [comment] 2021-07-30 07:41
I believe this has been fixed now, nitter.net has been running for a few weeks without any issues. Please reopen if it happens again, but please check the instance version so you don't report the issue happening on old ones.

**Closed by zedeus** 2021-07-30 07:41 UTC

**Comment by NebulaBC** [comment] 2022-01-05 00:54
I just got this error on my instance (public internet, but no one is using it)
I am running 2022.01.03-9a578b3 in docker, so it seems odd that I would get actually rate limited

**Comment by zedeus** [comment] 2022-01-05 10:18
@NebulaBC did it work before now, or did you just start seeing the error? Cloud IPs are generally banned by Twitter, though I've mostly heard reports regarding GCP and AWS.

**Comment by zedeus** [comment] 2022-01-06 02:21
@NebulaBC I've pushed some big changes to the API token pool just now, it should fix any remaining issues causing rate limits if it's not related to your Cloud provider
