### ISSUE TITLE
Searching for users return as 'No items found'

### ISSUE THREAD

**Issue by datanomi** [zedeus/nitter#481] opened 2021-12-18 14:01 UTC
Seems like this issue affects all instances, haven't found what could cause this.

<img width="868" alt="Screenshot 2021-12-18 at 16 01 20" src="https://user-images.githubusercontent.com/76632422/146643717-5dc73b55-a3d1-4c2a-b0e5-fb10c83e0dcc.png">
<img width="822" alt="Screenshot 2021-12-18 at 16 01 14" src="https://user-images.githubusercontent.com/76632422/146643718-e8c582ce-2bed-49c7-bb3f-8203dc1a147b.png">

**Comment by stemy2** [comment] 2021-12-18 18:07
It affects my instance too, and restarting the nitter service didn't fixed anything.

I think it's from the twitter's side.

**Comment by andreynering** [comment] 2021-12-18 23:16
Not only searching, but opening the user page directly also often shows "No items found". Sometimes a single/couple of refreshes work, but sometimes it won't show the content even after many refreshes.

---

Other than that, I'd like to thank the maintainer(s) for this project! With Twitter being more and more aggressive on not allowing unlogged users to view content, I found Nitter extremely useful!

**Comment by zedeus** [comment] 2021-12-19 15:59
It's been quite a while since most of nitter was implemented, so it's possible they've changed a few things. I haven't had time to investigate the cause, it could be anything from token retrieval logic to an opaque rate limit where they just serve 0 items.

**Comment by zedeus** [comment] 2021-12-19 20:53
Fixed by #483

**Closed by zedeus** 2021-12-19 20:53 UTC

**Comment by stemy2** [comment] 2021-12-22 18:29
The search function worked on the flagship instance for a while after your fix, but now, it fails again.

**Comment by stemy2** [comment] 2022-01-21 10:48
Could you reopen the issue ? It happens on my instance again. Restarting the nitter service didn't solved anything.

**Comment by datanomi** [comment] 2022-01-21 10:49
> Could you reopen the issue ? It happens on my instance again. Restarting the nitter service didn't solved anything.

Works on my instance, have you upgraded your instance of nitter?

**Comment by acarasimon96** [comment] 2022-01-21 18:07
It's happening on my private instance as well running [my own fork](https://github.com/acarasimon96/nitter-ft), which was brought up to date to the latest commit from here. Every time I open up any profile I see `429 Too Many Requests:` being printed out to the console and nothing more. This part of the site started breaking today; it was working just fine yesterday, so I suspect a change in the Twitter API might have occurred overnight.

**Comment by zedeus** [comment] 2022-01-21 20:36
It does not happen with the latest commit, please make sure you're running cdb4efa, check the about page.

**Comment by acarasimon96** [comment] 2022-01-21 21:27
It turns out that my fork was running a week behind in terms of commits. I just updated it moments ago, and now user profiles are working again. I even ran `redis-cli flushall` to make sure that the latest commit fixes this issue. Thanks @zedeus!

**Comment by jdqw210** [comment] 2022-02-13 21:55
> It does not happen with the latest commit, please make sure you're running [cdb4efa](https://github.com/zedeus/nitter/commit/cdb4efadfeb5102b501c7ff79261fefc7327edb9), check the about page.

How do I go about using this?

**Comment by zedeus** [comment] 2022-02-13 21:57
Recompile with the latest commit or use the latest docker tag
