### ISSUE TITLE
Add hability to retrieve view count for tweets in user timeline.

### ISSUE THREAD

**Issue by AntoinePaix** [zedeus/nitter#1033] opened 2023-09-25 13:13 UTC
You can activate the views count on the mobile app by adding an additional variable in the `variables` (this is the `variables` field and not `features`).

```Python
# add `rest_id` or `screen_name` according to endpoint
userMobileVariables = {
    'includeTweetImpression': True,
    'includeHasBirdwatchNotes': False,
    'includeEditPerspective': False,
    'includeEditControl': True,
    'count': 20,
    'includeTweetVisibilityNudge': True,
    'autoplay_enabled': True,
}
```

The field name is no longer `view` but `view_count_info` in the json response of the API.

**Comment by zedeus** [comment] 2023-09-25 13:38
Duplicate of #753

**Closed by zedeus** 2023-09-25 13:38 UTC
